<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"/>
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\services\healthcare\Matrix.Healthcare.Contracts\Matrix.Healthcare.Contracts.csproj"/>
    <ProjectReference Include="..\..\..\..\src\services\population\Matrix.Population.Infrastructure\Matrix.Population.Infrastructure.csproj"/>
    <ProjectReference Include="..\..\..\shared\Matrix.ArchitectureTesting\Matrix.ArchitectureTesting.csproj"/>
  </ItemGroup>

</Project>
