<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit"/>
    <PackageReference Include="MassTransit.RabbitMQ"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\building-blocks\Matrix.BuildingBlocks.Infrastructure\Matrix.BuildingBlocks.Infrastructure.csproj"/>
    <ProjectReference Include="..\Matrix.Education.Application\Matrix.Education.Application.csproj"/>
    <ProjectReference Include="..\Matrix.Education.Contracts\Matrix.Education.Contracts.csproj"/>
  </ItemGroup>

</Project>
