export const PermissionKeys = {
    IdentityUsersRead: "identity.admin.users.read",
    IdentityUsersLock: "identity.admin.users.lock",
    IdentityUsersUnlock: "identity.admin.users.unlock",
    IdentityUsersRestore: "identity.admin.users.restore",
    IdentityUserRolesRead: "identity.admin.users.roles.read",
    IdentityUserRolesUpdate: "identity.admin.users.roles.update",
    IdentityUserPermissionsRead: "identity.admin.users.permissions.read",
    IdentityUserPermissionsGrant: "identity.admin.users.permissions.grant",
    IdentityUserPermissionsDeprive: "identity.admin.users.permissions.deprive",
    IdentityUserSessionsRead: "identity.admin.users.sessions.read",
    IdentityUserSessionsRevoke: "identity.admin.users.sessions.revoke",
    IdentityUserSessionsRevokeAll: "identity.admin.users.sessions.revoke.all",
    IdentityRolesList: "identity.admin.roles.list",
    IdentityRolesCreate: "identity.admin.roles.create",
    IdentityRolesRename: "identity.admin.roles.rename",
    IdentityRolesDelete: "identity.admin.roles.delete",
    IdentityRolePermissionsRead: "identity.admin.roles.permissions.read",
    IdentityRolePermissionsUpdate: "identity.admin.roles.permissions.update",
    IdentityRoleMembersRead: "identity.admin.roles.members.read",
    IdentityPermissionsCatalogRead: "identity.admin.permissions.catalog.read",
    IdentityMeProfileRead: "identity.me.profile.read",
    IdentityMeDisplayNameChange: "identity.me.display-name.change",
    IdentityMeUsernameChange: "identity.me.username.change",
    IdentityMeEmailChange: "identity.me.email.change",
    IdentityMePasswordChange: "identity.me.password.change",
    IdentityMeAvatarChange: "identity.me.avatar.change",
    IdentityMeAccountDelete: "identity.me.account.delete",
    IdentityMeSessionsRead: "identity.me.sessions.read",
    IdentityMeSessionsRevoke: "identity.me.sessions.revoke",
    IdentityMeSessionsRevokeAll: "identity.me.sessions.revoke.all",
    SimulationCoreScenariosCatalogRead: "simulationcore.scenarios.catalog.read",
    SimulationCoreClassicCityRead: "simulationcore.classic-city.read",
    SimulationCoreClassicCityCreate: "simulationcore.classic-city.create",
    SimulationCoreClassicCityUpdate: "simulationcore.classic-city.update",
    SimulationCoreClassicCityArchive: "simulationcore.classic-city.archive",
    SimulationCoreClassicCityDelete: "simulationcore.classic-city.delete",
    SimulationCoreClassicCityPopulationBootstrapRetry: "simulationcore.classic-city.population-bootstrap.retry",
    SimulationCoreSimulationRead: "simulationcore.simulations.read",
    SimulationCoreSimulationControl: "simulationcore.simulations.control",
    PopulationPeopleInitialize: "population.people.initialize",
    PopulationPeopleRead: "population.people.read",
    PopulationCivilRegistryManage: "population.civil-registry.manage",
    PopulationEmploymentManage: "population.employment.manage",
    EducationEnrollmentsManage: "education.enrollments.manage",
    PopulationPersonResurrect: "population.person.resurrect",
    PopulationPersonKill: "population.person.kill",
    EconomyBudgetRead: "economy.budget.read",
    EconomyBusinessesRead: "economy.businesses.read",
    EconomyHouseholdAccountsRead: "economy.household-accounts.read",
} as const;

export type PermissionKey =
    (typeof PermissionKeys)[keyof typeof PermissionKeys];
