export const PermissionKeys = {
  IdentityAdminAccess: "identity.admin.access",
  IdentityUsersRead: "identity.admin.users.read",
  IdentityUsersLock: "identity.admin.users.lock",
  IdentityUsersUnlock: "identity.admin.users.unlock",
  IdentityUserRolesRead: "identity.admin.users.roles.read",
  IdentityUserRolesUpdate: "identity.admin.users.roles.update",
  IdentityUserPermissionsRead: "identity.admin.users.permissions.read",
  IdentityUserPermissionsGrant: "identity.admin.users.permissions.grant",
  IdentityUserPermissionsDeprive: "identity.admin.users.permissions.deprive",
  IdentityUserSessionsRead: "identity.admin.users.sessions.read",
  IdentityUserSessionsRevoke: "identity.admin.users.sessions.revoke",
  IdentityUserSessionsRevokeAll: "identity.admin.users.sessions.revoke.all",
  IdentityRolesList: "identity.admin.roles.list",
  IdentityRolesCreate: "identity.admin.roles.create",
  IdentityRolesRename: "identity.admin.roles.rename",
  IdentityRolesDelete: "identity.admin.roles.delete",
  IdentityRolePermissionsRead: "identity.admin.roles.permissions.read",
  IdentityRolePermissionsUpdate: "identity.admin.roles.permissions.update",
  IdentityRoleMembersRead: "identity.admin.roles.members.read",
  IdentityPermissionsCatalogRead: "identity.admin.permissions.catalog.read",
  IdentityMeProfileRead: "identity.me.profile.read",
  IdentityMePasswordChange: "identity.me.password.change",
  IdentityMeAvatarChange: "identity.me.avatar.change",
  IdentityMeSessionsRead: "identity.me.sessions.read",
  IdentityMeSessionsRevoke: "identity.me.sessions.revoke",
  IdentityMeSessionsRevokeAll: "identity.me.sessions.revoke.all",
  PopulationPeopleInitialize: "population.people.initialize",
  PopulationPeopleRead: "population.people.read",
  PopulationPersonResurrect: "population.person.resurrect",
  PopulationPersonKill: "population.person.kill",
} as const;

export type PermissionKey =
  (typeof PermissionKeys)[keyof typeof PermissionKeys];
