<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
    <PackageReference Include="MediatR"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\building-blocks\Matrix.BuildingBlocks.Application\Matrix.BuildingBlocks.Application.csproj"/>
    <ProjectReference Include="..\Matrix.SimulationCore.Domain\Matrix.SimulationCore.Domain.csproj"/>
  </ItemGroup>

</Project>
