<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>high</NuGetAuditLevel>
    <WarningsAsErrors>$(WarningsAsErrors);NU1903;NU1904</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup Condition="'$(UsingMicrosoftNETSdkWeb)' == 'true'">
    <Content Include="$(MSBuildThisFileDirectory)appsettings.logging.json" Link="appsettings.logging.json" CopyToOutputDirectory="PreserveNewest"/>
    <Content Include="$(MSBuildThisFileDirectory)appsettings.logging.Development.json" Link="appsettings.logging.Development.json" CopyToOutputDirectory="PreserveNewest"/>
  </ItemGroup>
</Project>
