<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\services\education\Matrix.Education.Contracts\Matrix.Education.Contracts.csproj"/>
    <ProjectReference Include="..\..\services\economy\Matrix.Economy.Contracts\Matrix.Economy.Contracts.csproj"/>
    <ProjectReference Include="..\..\services\resources\Matrix.Resources.Contracts\Matrix.Resources.Contracts.csproj"/>
    <ProjectReference Include="..\..\services\simulationcore\Matrix.SimulationCore.Contracts\Matrix.SimulationCore.Contracts.csproj"/>
    <ProjectReference Include="..\..\services\simulationsystems\Matrix.SimulationSystems.Contracts\Matrix.SimulationSystems.Contracts.csproj"/>
    <ProjectReference Include="..\Matrix.PermissionCatalog.Abstractions\Matrix.PermissionCatalog.Abstractions.csproj"/>
    <ProjectReference Include="..\..\services\identity\Matrix.Identity.Contracts\Matrix.Identity.Contracts.csproj"/>
    <ProjectReference Include="..\..\services\population\Matrix.Population.Contracts\Matrix.Population.Contracts.csproj"/>
  </ItemGroup>

</Project>
