using Matrix.SimulationCore.Domain.Scenarios.ClassicCity.Cities;

namespace Matrix.SimulationCore.Application.Scenarios.ClassicCity.UseCases.Cities.Common
{
    public sealed record CityDto(
        Guid CityId,
        Guid SimulationId,
        string Name,
        string SimulationKind,
        string Status,
        string ClimateZone,
        string Hemisphere,
        int UtcOffsetMinutes,
        string GenerationSeed,
        Guid RunId,
        string ScenarioModelSetVersion,
        string SizeTier,
        string UrbanDensity,
        string DevelopmentLevel,
        string EconomyProfile,
        string PopulationOccupancyProfile,
        int? PlannedPeopleCount,
        Guid PopulationBootstrapOperationId,
        Guid EconomyBootstrapOperationId,
        DateTimeOffset CreatedAtUtc,
        DateTimeOffset? PopulationBootstrapCompletedAtUtc,
        DateTimeOffset? EconomyBootstrapCompletedAtUtc,
        DateTimeOffset? PopulationBootstrapFailedAtUtc,
        DateTimeOffset? EconomyBootstrapFailedAtUtc,
        string? PopulationBootstrapFailureCode,
        string? EconomyBootstrapFailureCode,
        DateTimeOffset? ProvisioningStartedAtUtc,
        DateTimeOffset? ProvisioningHeartbeatAtUtc,
        DateTimeOffset? ProvisioningLeaseExpiresAtUtc,
        int ProvisioningAttemptCount,
        DateTimeOffset? ArchivedAtUtc,
        bool IsArchived)
    {
        public static CityDto FromDomain(City city)
        {
            return new CityDto(
                CityId: city.Id.Value,
                SimulationId: city.Id.Value,
                Name: city.Name.Value,
                SimulationKind: Matrix.SimulationCore.Domain.Simulation.SimulationKind.ClassicCity.ToString(),
                Status: city.Status.ToString(),
                ClimateZone: city.Environment.ClimateZone.ToString(),
                Hemisphere: city.Environment.Hemisphere.ToString(),
                UtcOffsetMinutes: city.Environment.UtcOffset.TotalMinutes,
                GenerationSeed: city.GenerationSeed.Value,
                RunId: city.RunId,
                ScenarioModelSetVersion: city.ScenarioModelSetVersion.Value,
                SizeTier: city.GenerationProfile.SizeTier.ToString(),
                UrbanDensity: city.GenerationProfile.UrbanDensity.ToString(),
                DevelopmentLevel: city.GenerationProfile.DevelopmentLevel.ToString(),
                EconomyProfile: city.GenerationProfile.EconomyProfile.ToString(),
                PopulationOccupancyProfile: city.GenerationProfile.PopulationOccupancyProfile.ToString(),
                PlannedPeopleCount: city.GenerationProfile.PlannedPeopleCount,
                PopulationBootstrapOperationId: city.PopulationBootstrapOperationId,
                EconomyBootstrapOperationId: city.EconomyBootstrapOperationId,
                CreatedAtUtc: city.CreatedAtUtc,
                PopulationBootstrapCompletedAtUtc: city.PopulationBootstrapCompletedAtUtc,
                EconomyBootstrapCompletedAtUtc: city.EconomyBootstrapCompletedAtUtc,
                PopulationBootstrapFailedAtUtc: city.PopulationBootstrapFailedAtUtc,
                EconomyBootstrapFailedAtUtc: city.EconomyBootstrapFailedAtUtc,
                PopulationBootstrapFailureCode: city.PopulationBootstrapFailureCode,
                EconomyBootstrapFailureCode: city.EconomyBootstrapFailureCode,
                ProvisioningStartedAtUtc: city.ProvisioningStartedAtUtc,
                ProvisioningHeartbeatAtUtc: city.ProvisioningHeartbeatAtUtc,
                ProvisioningLeaseExpiresAtUtc: city.ProvisioningLeaseExpiresAtUtc,
                ProvisioningAttemptCount: city.ProvisioningAttemptCount,
                ArchivedAtUtc: city.ArchivedAtUtc,
                IsArchived: city.IsArchived);
        }
    }
}
