// <auto-generated />
using System;
using Matrix.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20251210170710_AddIsPersistentRefreshToken2")]
    partial class AddIsPersistentRefreshToken2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.User", b =>
                {
                    b.OwnsMany("Matrix.Identity.Domain.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("ExpiresAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsPersistent")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsRevoked")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true);

                            b1.Property<DateTime?>("LastUsedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("TokenHash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TokenHash");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserRefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("Matrix.Identity.Domain.ValueObjects.DeviceInfo", "DeviceInfo", b2 =>
                                {
                                    b2.Property<Guid>("RefreshTokenId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("DeviceId")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("DeviceId");

                                    b2.Property<string>("DeviceName")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("DeviceName");

                                    b2.Property<string>("IpAddress")
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("IpAddress");

                                    b2.Property<string>("UserAgent")
                                        .IsRequired()
                                        .HasMaxLength(512)
                                        .HasColumnType("character varying(512)")
                                        .HasColumnName("UserAgent");

                                    b2.HasKey("RefreshTokenId");

                                    b2.ToTable("UserRefreshTokens");

                                    b2.WithOwner()
                                        .HasForeignKey("RefreshTokenId");
                                });

                            b1.OwnsOne("Matrix.Identity.Domain.ValueObjects.GeoLocation", "GeoLocation", b2 =>
                                {
                                    b2.Property<Guid>("RefreshTokenId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("City");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("Country");

                                    b2.Property<string>("Region")
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("Region");

                                    b2.HasKey("RefreshTokenId");

                                    b2.ToTable("UserRefreshTokens");

                                    b2.WithOwner()
                                        .HasForeignKey("RefreshTokenId");
                                });

                            b1.Navigation("DeviceInfo")
                                .IsRequired();

                            b1.Navigation("GeoLocation");
                        });

                    b.OwnsOne("Matrix.Identity.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Matrix.Identity.Domain.ValueObjects.Username", "Username", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("Username");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("RefreshTokens");

                    b.Navigation("Username")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
