// <auto-generated />
using System;
using Matrix.CityCore.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.CityCore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CityCoreDbContext))]
    [Migration("20260312123614_AddCityProvisioningLifecycle")]
    partial class AddCityProvisioningLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.BuildingBlocks.Infrastructure.Outbox.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAttemptOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextAttemptOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "LockedUntilUtc", "NextAttemptOnUtc", "OccurredOnUtc")
                        .HasFilter("\"ProcessedOnUtc\" IS NULL");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Matrix.CityCore.Domain.Cities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GenerationSeed")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("PopulationBootstrapCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PopulationBootstrapFailureCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("PopulationBootstrapFailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PopulationBootstrapOperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Matrix.CityCore.Domain.Simulation.SimulationClock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CurrentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Speed")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("TickId")
                        .HasColumnType("bigint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("SimulationClocks", (string)null);
                });

            modelBuilder.Entity("Matrix.CityCore.Domain.Topology.District", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("Matrix.CityCore.Domain.Topology.ResidentialBuilding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("ResidentCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.ToTable("ResidentialBuildings", (string)null);
                });

            modelBuilder.Entity("Matrix.CityCore.Domain.Weather.CityWeather", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastTransitionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("CityWeathers", (string)null);
                });

            modelBuilder.Entity("Matrix.CityCore.Domain.Cities.City", b =>
                {
                    b.OwnsOne("Matrix.CityCore.Domain.Cities.CityEnvironment", "Environment", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ClimateZone")
                                .HasColumnType("integer")
                                .HasColumnName("ClimateZone");

                            b1.Property<int>("Hemisphere")
                                .HasColumnType("integer")
                                .HasColumnName("Hemisphere");

                            b1.Property<int>("UtcOffset")
                                .HasColumnType("integer")
                                .HasColumnName("UtcOffsetMinutes");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.OwnsOne("Matrix.CityCore.Domain.Cities.CityGenerationProfile", "GenerationProfile", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DevelopmentLevel")
                                .HasColumnType("integer")
                                .HasColumnName("GenerationDevelopmentLevel");

                            b1.Property<int>("SizeTier")
                                .HasColumnType("integer")
                                .HasColumnName("GenerationSizeTier");

                            b1.Property<int>("UrbanDensity")
                                .HasColumnType("integer")
                                .HasColumnName("GenerationUrbanDensity");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("Environment")
                        .IsRequired();

                    b.Navigation("GenerationProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("Matrix.CityCore.Domain.Simulation.SimulationClock", b =>
                {
                    b.HasOne("Matrix.CityCore.Domain.Cities.City", null)
                        .WithOne()
                        .HasForeignKey("Matrix.CityCore.Domain.Simulation.SimulationClock", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Matrix.CityCore.Domain.Topology.District", b =>
                {
                    b.HasOne("Matrix.CityCore.Domain.Cities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Matrix.CityCore.Domain.Topology.ResidentialBuilding", b =>
                {
                    b.HasOne("Matrix.CityCore.Domain.Cities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matrix.CityCore.Domain.Topology.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Matrix.CityCore.Domain.Weather.CityWeather", b =>
                {
                    b.HasOne("Matrix.CityCore.Domain.Cities.City", null)
                        .WithOne()
                        .HasForeignKey("Matrix.CityCore.Domain.Weather.CityWeather", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Matrix.CityCore.Domain.Weather.WeatherOverride", "ActiveOverride", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("uuid")
                                .HasColumnName("CityId");

                            b1.Property<DateTimeOffset>("EndsAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("EndsAt");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("OverrideId");

                            b1.Property<string>("Reason")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Reason");

                            b1.Property<int>("Source")
                                .HasColumnType("integer")
                                .HasColumnName("Source");

                            b1.Property<DateTimeOffset>("StartsAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartsAt");

                            b1.HasKey("CityId");

                            b1.ToTable("CityWeatherOverrides", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CityId");

                            b1.OwnsOne("Matrix.CityCore.Domain.Weather.WeatherState", "ForcedState", b2 =>
                                {
                                    b2.Property<Guid>("WeatherOverrideCityId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("CloudCoverage")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("numeric(5,2)")
                                        .HasColumnName("ForcedCloudCoveragePercent");

                                    b2.Property<DateTimeOffset>("ExpectedUntil")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("ForcedExpectedUntil");

                                    b2.Property<decimal>("Humidity")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("numeric(5,2)")
                                        .HasColumnName("ForcedHumidityPercent");

                                    b2.Property<int>("PrecipitationKind")
                                        .HasColumnType("integer")
                                        .HasColumnName("ForcedPrecipitationKind");

                                    b2.Property<decimal>("Pressure")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("ForcedPressureHpa");

                                    b2.Property<int>("Severity")
                                        .HasColumnType("integer")
                                        .HasColumnName("ForcedSeverity");

                                    b2.Property<DateTimeOffset>("StartedAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("ForcedStartedAt");

                                    b2.Property<decimal>("Temperature")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("ForcedTemperatureC");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer")
                                        .HasColumnName("ForcedType");

                                    b2.Property<decimal>("WindSpeed")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("ForcedWindSpeedKph");

                                    b2.HasKey("WeatherOverrideCityId");

                                    b2.ToTable("CityWeatherOverrides");

                                    b2.WithOwner()
                                        .HasForeignKey("WeatherOverrideCityId");
                                });

                            b1.Navigation("ForcedState")
                                .IsRequired();
                        });

                    b.OwnsOne("Matrix.CityCore.Domain.Weather.WeatherState", "CurrentState", b1 =>
                        {
                            b1.Property<Guid>("CityWeatherId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("CloudCoverage")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("CurrentCloudCoveragePercent");

                            b1.Property<DateTimeOffset>("ExpectedUntil")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CurrentExpectedUntil");

                            b1.Property<decimal>("Humidity")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("CurrentHumidityPercent");

                            b1.Property<int>("PrecipitationKind")
                                .HasColumnType("integer")
                                .HasColumnName("CurrentPrecipitationKind");

                            b1.Property<decimal>("Pressure")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("CurrentPressureHpa");

                            b1.Property<int>("Severity")
                                .HasColumnType("integer")
                                .HasColumnName("CurrentSeverity");

                            b1.Property<DateTimeOffset>("StartedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CurrentStartedAt");

                            b1.Property<decimal>("Temperature")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("CurrentTemperatureC");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("CurrentType");

                            b1.Property<decimal>("WindSpeed")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("CurrentWindSpeedKph");

                            b1.HasKey("CityWeatherId");

                            b1.ToTable("CityWeathers");

                            b1.WithOwner()
                                .HasForeignKey("CityWeatherId");
                        });

                    b.OwnsOne("Matrix.CityCore.Domain.Weather.WeatherClimateProfile", "ClimateProfile", b1 =>
                        {
                            b1.Property<Guid>("CityWeatherId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ClimateZone")
                                .HasColumnType("integer")
                                .HasColumnName("ClimateZone");

                            b1.Property<decimal>("Volatility")
                                .HasPrecision(4, 3)
                                .HasColumnType("numeric(4,3)")
                                .HasColumnName("Volatility");

                            b1.HasKey("CityWeatherId");

                            b1.ToTable("CityWeathers");

                            b1.WithOwner()
                                .HasForeignKey("CityWeatherId");

                            b1.OwnsOne("Matrix.CityCore.Domain.Weather.Profiles.ExtremeWeatherProfile", "ExtremeWeatherProfile", b2 =>
                                {
                                    b2.Property<Guid>("WeatherClimateProfileCityWeatherId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("MaxOverallSeverity")
                                        .HasColumnType("integer")
                                        .HasColumnName("ExtremeMaxOverallSeverity");

                                    b2.Property<bool>("SupportsFog")
                                        .HasColumnType("boolean")
                                        .HasColumnName("ExtremeSupportsFog");

                                    b2.Property<bool>("SupportsHeatwaves")
                                        .HasColumnType("boolean")
                                        .HasColumnName("ExtremeSupportsHeatwaves");

                                    b2.Property<bool>("SupportsSnowstorms")
                                        .HasColumnType("boolean")
                                        .HasColumnName("ExtremeSupportsSnowstorms");

                                    b2.Property<bool>("SupportsThunderstorms")
                                        .HasColumnType("boolean")
                                        .HasColumnName("ExtremeSupportsThunderstorms");

                                    b2.HasKey("WeatherClimateProfileCityWeatherId");

                                    b2.ToTable("CityWeathers");

                                    b2.WithOwner()
                                        .HasForeignKey("WeatherClimateProfileCityWeatherId");
                                });

                            b1.OwnsOne("Matrix.CityCore.Domain.Weather.Profiles.SeasonalPrecipitationProfile", "PrecipitationProfile", b2 =>
                                {
                                    b2.Property<Guid>("WeatherClimateProfileCityWeatherId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("AutumnDominantKind")
                                        .HasColumnType("integer")
                                        .HasColumnName("PrecipitationAutumnDominantKind");

                                    b2.Property<decimal>("AutumnHumidity")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("numeric(5,2)")
                                        .HasColumnName("PrecipitationAutumnHumidity");

                                    b2.Property<int>("SpringDominantKind")
                                        .HasColumnType("integer")
                                        .HasColumnName("PrecipitationSpringDominantKind");

                                    b2.Property<decimal>("SpringHumidity")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("numeric(5,2)")
                                        .HasColumnName("PrecipitationSpringHumidity");

                                    b2.Property<int>("SummerDominantKind")
                                        .HasColumnType("integer")
                                        .HasColumnName("PrecipitationSummerDominantKind");

                                    b2.Property<decimal>("SummerHumidity")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("numeric(5,2)")
                                        .HasColumnName("PrecipitationSummerHumidity");

                                    b2.Property<int>("WinterDominantKind")
                                        .HasColumnType("integer")
                                        .HasColumnName("PrecipitationWinterDominantKind");

                                    b2.Property<decimal>("WinterHumidity")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("numeric(5,2)")
                                        .HasColumnName("PrecipitationWinterHumidity");

                                    b2.HasKey("WeatherClimateProfileCityWeatherId");

                                    b2.ToTable("CityWeathers");

                                    b2.WithOwner()
                                        .HasForeignKey("WeatherClimateProfileCityWeatherId");
                                });

                            b1.OwnsOne("Matrix.CityCore.Domain.Weather.Profiles.SeasonalTemperatureProfile", "TemperatureProfile", b2 =>
                                {
                                    b2.Property<Guid>("WeatherClimateProfileCityWeatherId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("AutumnAverage")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("TemperatureAutumnAverage");

                                    b2.Property<decimal>("DailySwing")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("TemperatureDailySwing");

                                    b2.Property<decimal>("SpringAverage")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("TemperatureSpringAverage");

                                    b2.Property<decimal>("SummerAverage")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("TemperatureSummerAverage");

                                    b2.Property<decimal>("WinterAverage")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("TemperatureWinterAverage");

                                    b2.HasKey("WeatherClimateProfileCityWeatherId");

                                    b2.ToTable("CityWeathers");

                                    b2.WithOwner()
                                        .HasForeignKey("WeatherClimateProfileCityWeatherId");
                                });

                            b1.OwnsOne("Matrix.CityCore.Domain.Weather.Profiles.SeasonalWindProfile", "WindProfile", b2 =>
                                {
                                    b2.Property<Guid>("WeatherClimateProfileCityWeatherId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("AutumnAverage")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("WindAutumnAverage");

                                    b2.Property<decimal>("GustHeadroom")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("WindGustHeadroom");

                                    b2.Property<decimal>("SpringAverage")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("WindSpringAverage");

                                    b2.Property<decimal>("SummerAverage")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("WindSummerAverage");

                                    b2.Property<decimal>("WinterAverage")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("WindWinterAverage");

                                    b2.HasKey("WeatherClimateProfileCityWeatherId");

                                    b2.ToTable("CityWeathers");

                                    b2.WithOwner()
                                        .HasForeignKey("WeatherClimateProfileCityWeatherId");
                                });

                            b1.Navigation("ExtremeWeatherProfile")
                                .IsRequired();

                            b1.Navigation("PrecipitationProfile")
                                .IsRequired();

                            b1.Navigation("TemperatureProfile")
                                .IsRequired();

                            b1.Navigation("WindProfile")
                                .IsRequired();
                        });

                    b.Navigation("ActiveOverride");

                    b.Navigation("ClimateProfile")
                        .IsRequired();

                    b.Navigation("CurrentState")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
