<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation"/>
    <PackageReference Include="MediatR"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Matrix.BuildingBlocks.Domain\Matrix.BuildingBlocks.Domain.csproj"/>
  </ItemGroup>

</Project>
