// <auto-generated />
using System;
using Matrix.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260111143340_AddRoleNormalizedName")]
    partial class AddRoleNormalizedName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.OneTimeToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OneTimeTokens", (string)null);
                });

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.Permission", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Key");

                    b.HasIndex("Group");

                    b.HasIndex("IsDeprecated");

                    b.HasIndex("Service");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_normalized_name");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("RoleId", "PermissionKey");

                    b.HasIndex("PermissionKey");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PermissionsVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.UserPermissionOverride", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte>("Effect")
                        .HasColumnType("smallint");

                    b.HasKey("UserId", "PermissionKey");

                    b.HasIndex("Effect");

                    b.HasIndex("PermissionKey");

                    b.ToTable("UserPermissionOverrides", (string)null);
                });

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.OneTimeToken", b =>
                {
                    b.HasOne("Matrix.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Matrix.Identity.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matrix.Identity.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.User", b =>
                {
                    b.OwnsMany("Matrix.Identity.Domain.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("ExpiresAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsPersistent")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true);

                            b1.Property<bool>("IsRevoked")
                                .HasColumnType("boolean");

                            b1.Property<DateTime?>("LastUsedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("RevokedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("RevokedReason")
                                .HasColumnType("text");

                            b1.Property<string>("TokenHash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TokenHash");

                            b1.HasIndex("UserId", "ExpiresAtUtc");

                            b1.HasIndex("UserId", "IsRevoked");

                            b1.ToTable("UserRefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsOne("Matrix.Identity.Domain.ValueObjects.DeviceInfo", "DeviceInfo", b2 =>
                                {
                                    b2.Property<Guid>("RefreshTokenId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("DeviceId")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("DeviceId");

                                    b2.Property<string>("DeviceName")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("DeviceName");

                                    b2.Property<string>("IpAddress")
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("IpAddress");

                                    b2.Property<string>("UserAgent")
                                        .IsRequired()
                                        .HasMaxLength(512)
                                        .HasColumnType("character varying(512)")
                                        .HasColumnName("UserAgent");

                                    b2.HasKey("RefreshTokenId");

                                    b2.ToTable("UserRefreshTokens");

                                    b2.WithOwner()
                                        .HasForeignKey("RefreshTokenId");
                                });

                            b1.OwnsOne("Matrix.Identity.Domain.ValueObjects.GeoLocation", "GeoLocation", b2 =>
                                {
                                    b2.Property<Guid>("RefreshTokenId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("City")
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("City");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("Country");

                                    b2.Property<string>("Region")
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("Region");

                                    b2.HasKey("RefreshTokenId");

                                    b2.ToTable("UserRefreshTokens");

                                    b2.WithOwner()
                                        .HasForeignKey("RefreshTokenId");
                                });

                            b1.Navigation("DeviceInfo")
                                .IsRequired();

                            b1.Navigation("GeoLocation");
                        });

                    b.OwnsOne("Matrix.Identity.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Matrix.Identity.Domain.ValueObjects.Username", "Username", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("Username");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("RefreshTokens");

                    b.Navigation("Username")
                        .IsRequired();
                });

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.UserPermissionOverride", b =>
                {
                    b.HasOne("Matrix.Identity.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matrix.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Matrix.Identity.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Matrix.Identity.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matrix.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
