<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit"/>
    <PackageReference Include="MassTransit.RabbitMQ"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\building-blocks\Matrix.BuildingBlocks.Application\Matrix.BuildingBlocks.Application.csproj"/>
    <ProjectReference Include="..\..\..\building-blocks\Matrix.BuildingBlocks.Infrastructure\Matrix.BuildingBlocks.Infrastructure.csproj"/>
    <ProjectReference Include="..\..\economy\Matrix.Economy.Contracts\Matrix.Economy.Contracts.csproj"/>
    <ProjectReference Include="..\..\simulationcore\Matrix.SimulationCore.Contracts\Matrix.SimulationCore.Contracts.csproj"/>
    <ProjectReference Include="..\Matrix.Resources.Application\Matrix.Resources.Application.csproj"/>
  </ItemGroup>

</Project>
