// <auto-generated />
using System;
using Matrix.SimulationSystems.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.SimulationSystems.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SimulationSystemsDbContext))]
    [Migration("20260417124105_AddEnvironmentalWeatherPressure")]
    partial class AddEnvironmentalWeatherPressure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityEnvironmentalConditionState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FloodingIndex")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTimeOffset>("LastEvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RoadAccessibilityIndex")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("SnowAccumulationIndex")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("CityEnvironmentalConditions", (string)null);
                });

            modelBuilder.Entity("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityEnvironmentalConditionState", b =>
                {
                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Models.CityWeatherPressureProfile", "WeatherPressure", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("FreezePressure")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WeatherFreezePressure");

                            b1.Property<decimal>("RainPressure")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WeatherRainPressure");

                            b1.Property<decimal>("SnowPressure")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WeatherSnowPressure");

                            b1.Property<decimal>("StormPressure")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WeatherStormPressure");

                            b1.Property<decimal>("ThawRelief")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WeatherThawRelief");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CitySystemState", "Drainage", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BacklogIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("DrainageBacklogIndex");

                            b1.Property<decimal>("FailureRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("DrainageFailureRiskIndex");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("DrainageKind");

                            b1.Property<decimal>("LoadIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("DrainageLoadIndex");

                            b1.Property<decimal>("ServiceQualityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("DrainageServiceQualityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CitySystemState", "RoadAccess", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BacklogIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("RoadAccessBacklogIndex");

                            b1.Property<decimal>("FailureRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("RoadAccessFailureRiskIndex");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("RoadAccessKind");

                            b1.Property<decimal>("LoadIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("RoadAccessLoadIndex");

                            b1.Property<decimal>("ServiceQualityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("RoadAccessServiceQualityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CitySystemState", "SnowRemoval", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BacklogIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SnowRemovalBacklogIndex");

                            b1.Property<decimal>("FailureRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SnowRemovalFailureRiskIndex");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("SnowRemovalKind");

                            b1.Property<decimal>("LoadIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SnowRemovalLoadIndex");

                            b1.Property<decimal>("ServiceQualityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SnowRemovalServiceQualityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.Navigation("Drainage")
                        .IsRequired();

                    b.Navigation("RoadAccess")
                        .IsRequired();

                    b.Navigation("SnowRemoval")
                        .IsRequired();

                    b.Navigation("WeatherPressure")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
