// <auto-generated />
using System;
using Matrix.SimulationSystems.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.SimulationSystems.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SimulationSystemsDbContext))]
    [Migration("20260419040233_AddPendingOperationFocusDistricts")]
    partial class AddPendingOperationFocusDistricts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.BuildingBlocks.Infrastructure.Outbox.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAttemptOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextAttemptOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "LockedUntilUtc", "NextAttemptOnUtc", "OccurredOnUtc")
                        .HasFilter("\"ProcessedOnUtc\" IS NULL");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityEnvironmentalConditionState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FloodingIndex")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("HeatingCoverageIndex")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<long>("LastAppliedTickId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastEvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PowerCoverageIndex")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("RoadAccessibilityIndex")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("SanitationCoverageIndex")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("SnowAccumulationIndex")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("UtilityContinuityIndex")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("WaterCoverageIndex")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("CityEnvironmentalConditions", (string)null);
                });

            modelBuilder.Entity("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityEnvironmentalConditionState", b =>
                {
                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Models.CityWeatherPressureProfile", "WeatherPressure", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("FreezePressure")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WeatherFreezePressure");

                            b1.Property<decimal>("RainPressure")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WeatherRainPressure");

                            b1.Property<decimal>("SnowPressure")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WeatherSnowPressure");

                            b1.Property<decimal>("StormPressure")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WeatherStormPressure");

                            b1.Property<decimal>("ThawRelief")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WeatherThawRelief");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityDrainageInfrastructureState", "DrainageInfrastructure", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BlockageIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("DrainageBlockageIndex");

                            b1.Property<decimal>("CrewReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("DrainageCrewReadinessIndex");

                            b1.Property<bool>("EmergencyModeEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("DrainageEmergencyModeEnabled");

                            b1.Property<decimal>("IncidentPressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("DrainageIncidentPressureIndex");

                            b1.Property<decimal>("NetworkIntegrityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("DrainageNetworkIntegrityIndex");

                            b1.Property<decimal>("PumpCapacityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("DrainagePumpCapacityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CitySystemState", "Drainage", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BacklogIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("DrainageBacklogIndex");

                            b1.Property<decimal>("FailureRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("DrainageFailureRiskIndex");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("DrainageKind");

                            b1.Property<decimal>("LoadIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("DrainageLoadIndex");

                            b1.Property<decimal>("ServiceQualityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("DrainageServiceQualityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CitySystemState", "Heating", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BacklogIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("HeatingBacklogIndex");

                            b1.Property<decimal>("FailureRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("HeatingFailureRiskIndex");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("HeatingKind");

                            b1.Property<decimal>("LoadIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("HeatingLoadIndex");

                            b1.Property<decimal>("ServiceQualityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("HeatingServiceQualityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityPendingOperationalWorkState", "PendingDrainageMaintenance", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Focus")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("PendingDrainageMaintenanceFocus");

                            b1.Property<Guid?>("FocusDistrictId")
                                .HasColumnType("uuid")
                                .HasColumnName("PendingDrainageMaintenanceFocusDistrictId");

                            b1.Property<string>("Intensity")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("PendingDrainageMaintenanceIntensity");

                            b1.Property<bool>("IsScheduled")
                                .HasColumnType("boolean")
                                .HasColumnName("PendingDrainageMaintenanceIsScheduled");

                            b1.Property<long>("ReadyAtTickId")
                                .HasColumnType("bigint")
                                .HasColumnName("PendingDrainageMaintenanceReadyAtTickId");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityPendingOperationalWorkState", "PendingHeatingMaintenance", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Focus")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("PendingHeatingMaintenanceFocus");

                            b1.Property<Guid?>("FocusDistrictId")
                                .HasColumnType("uuid")
                                .HasColumnName("PendingHeatingMaintenanceFocusDistrictId");

                            b1.Property<string>("Intensity")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("PendingHeatingMaintenanceIntensity");

                            b1.Property<bool>("IsScheduled")
                                .HasColumnType("boolean")
                                .HasColumnName("PendingHeatingMaintenanceIsScheduled");

                            b1.Property<long>("ReadyAtTickId")
                                .HasColumnType("bigint")
                                .HasColumnName("PendingHeatingMaintenanceReadyAtTickId");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityPendingOperationalWorkState", "PendingPowerDistributionMaintenance", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Focus")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("PendingPowerDistributionMaintenanceFocus");

                            b1.Property<Guid?>("FocusDistrictId")
                                .HasColumnType("uuid")
                                .HasColumnName("PendingPowerDistributionMaintenanceFocusDistrictId");

                            b1.Property<string>("Intensity")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("PendingPowerDistributionMaintenanceIntensity");

                            b1.Property<bool>("IsScheduled")
                                .HasColumnType("boolean")
                                .HasColumnName("PendingPowerDistributionMaintenanceIsScheduled");

                            b1.Property<long>("ReadyAtTickId")
                                .HasColumnType("bigint")
                                .HasColumnName("PendingPowerDistributionMaintenanceReadyAtTickId");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityPendingOperationalWorkState", "PendingRoadAccessMaintenance", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Focus")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("PendingRoadAccessMaintenanceFocus");

                            b1.Property<Guid?>("FocusDistrictId")
                                .HasColumnType("uuid")
                                .HasColumnName("PendingRoadAccessMaintenanceFocusDistrictId");

                            b1.Property<string>("Intensity")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("PendingRoadAccessMaintenanceIntensity");

                            b1.Property<bool>("IsScheduled")
                                .HasColumnType("boolean")
                                .HasColumnName("PendingRoadAccessMaintenanceIsScheduled");

                            b1.Property<long>("ReadyAtTickId")
                                .HasColumnType("bigint")
                                .HasColumnName("PendingRoadAccessMaintenanceReadyAtTickId");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityPendingOperationalWorkState", "PendingSanitationMaintenance", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Focus")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("PendingSanitationMaintenanceFocus");

                            b1.Property<Guid?>("FocusDistrictId")
                                .HasColumnType("uuid")
                                .HasColumnName("PendingSanitationMaintenanceFocusDistrictId");

                            b1.Property<string>("Intensity")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("PendingSanitationMaintenanceIntensity");

                            b1.Property<bool>("IsScheduled")
                                .HasColumnType("boolean")
                                .HasColumnName("PendingSanitationMaintenanceIsScheduled");

                            b1.Property<long>("ReadyAtTickId")
                                .HasColumnType("bigint")
                                .HasColumnName("PendingSanitationMaintenanceReadyAtTickId");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityPendingOperationalWorkState", "PendingSnowRemovalMaintenance", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Focus")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("PendingSnowRemovalMaintenanceFocus");

                            b1.Property<Guid?>("FocusDistrictId")
                                .HasColumnType("uuid")
                                .HasColumnName("PendingSnowRemovalMaintenanceFocusDistrictId");

                            b1.Property<string>("Intensity")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("PendingSnowRemovalMaintenanceIntensity");

                            b1.Property<bool>("IsScheduled")
                                .HasColumnType("boolean")
                                .HasColumnName("PendingSnowRemovalMaintenanceIsScheduled");

                            b1.Property<long>("ReadyAtTickId")
                                .HasColumnType("bigint")
                                .HasColumnName("PendingSnowRemovalMaintenanceReadyAtTickId");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityPendingOperationalWorkState", "PendingUtilityIncidentResponse", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Focus")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("PendingUtilityIncidentResponseFocus");

                            b1.Property<Guid?>("FocusDistrictId")
                                .HasColumnType("uuid")
                                .HasColumnName("PendingUtilityIncidentResponseFocusDistrictId");

                            b1.Property<string>("Intensity")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("PendingUtilityIncidentResponseIntensity");

                            b1.Property<bool>("IsScheduled")
                                .HasColumnType("boolean")
                                .HasColumnName("PendingUtilityIncidentResponseIsScheduled");

                            b1.Property<long>("ReadyAtTickId")
                                .HasColumnType("bigint")
                                .HasColumnName("PendingUtilityIncidentResponseReadyAtTickId");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityPendingOperationalWorkState", "PendingWaterDistributionMaintenance", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Focus")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("PendingWaterDistributionMaintenanceFocus");

                            b1.Property<Guid?>("FocusDistrictId")
                                .HasColumnType("uuid")
                                .HasColumnName("PendingWaterDistributionMaintenanceFocusDistrictId");

                            b1.Property<string>("Intensity")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("PendingWaterDistributionMaintenanceIntensity");

                            b1.Property<bool>("IsScheduled")
                                .HasColumnType("boolean")
                                .HasColumnName("PendingWaterDistributionMaintenanceIsScheduled");

                            b1.Property<long>("ReadyAtTickId")
                                .HasColumnType("bigint")
                                .HasColumnName("PendingWaterDistributionMaintenanceReadyAtTickId");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CitySystemState", "PowerDistribution", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BacklogIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("PowerDistributionBacklogIndex");

                            b1.Property<decimal>("FailureRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("PowerDistributionFailureRiskIndex");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("PowerDistributionKind");

                            b1.Property<decimal>("LoadIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("PowerDistributionLoadIndex");

                            b1.Property<decimal>("ServiceQualityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("PowerDistributionServiceQualityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CitySystemState", "RoadAccess", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BacklogIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("RoadAccessBacklogIndex");

                            b1.Property<decimal>("FailureRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("RoadAccessFailureRiskIndex");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("RoadAccessKind");

                            b1.Property<decimal>("LoadIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("RoadAccessLoadIndex");

                            b1.Property<decimal>("ServiceQualityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("RoadAccessServiceQualityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CitySystemState", "Sanitation", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BacklogIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SanitationBacklogIndex");

                            b1.Property<decimal>("FailureRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SanitationFailureRiskIndex");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("SanitationKind");

                            b1.Property<decimal>("LoadIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SanitationLoadIndex");

                            b1.Property<decimal>("ServiceQualityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SanitationServiceQualityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CitySystemState", "SnowRemoval", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BacklogIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SnowRemovalBacklogIndex");

                            b1.Property<decimal>("FailureRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SnowRemovalFailureRiskIndex");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("SnowRemovalKind");

                            b1.Property<decimal>("LoadIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SnowRemovalLoadIndex");

                            b1.Property<decimal>("ServiceQualityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SnowRemovalServiceQualityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CitySystemState", "UtilityIncidents", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BacklogIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("UtilityIncidentsBacklogIndex");

                            b1.Property<decimal>("FailureRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("UtilityIncidentsFailureRiskIndex");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("UtilityIncidentsKind");

                            b1.Property<decimal>("LoadIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("UtilityIncidentsLoadIndex");

                            b1.Property<decimal>("ServiceQualityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("UtilityIncidentsServiceQualityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CitySystemState", "WaterDistribution", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BacklogIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WaterDistributionBacklogIndex");

                            b1.Property<decimal>("FailureRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WaterDistributionFailureRiskIndex");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("WaterDistributionKind");

                            b1.Property<decimal>("LoadIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WaterDistributionLoadIndex");

                            b1.Property<decimal>("ServiceQualityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WaterDistributionServiceQualityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityHeatingInfrastructureState", "HeatingInfrastructure", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("ControlReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("HeatingControlReadinessIndex");

                            b1.Property<decimal>("CrewReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("HeatingCrewReadinessIndex");

                            b1.Property<bool>("EmergencyModeEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("HeatingEmergencyModeEnabled");

                            b1.Property<decimal>("IncidentPressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("HeatingIncidentPressureIndex");

                            b1.Property<decimal>("NetworkIntegrityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("HeatingNetworkIntegrityIndex");

                            b1.Property<decimal>("PlantCapacityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("HeatingPlantCapacityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityOperationalBudgetPressureState", "OperationalBudgetPressure", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Balance")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BudgetPressureBalance");

                            b1.Property<DateTimeOffset>("EffectiveAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("BudgetPressureEffectiveAtUtc");

                            b1.Property<long>("EffectiveTickId")
                                .HasColumnType("bigint")
                                .HasColumnName("BudgetPressureEffectiveTickId");

                            b1.Property<string>("GeneralAuthorizationLevel")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("BudgetPressureGeneralAuthorizationLevel");

                            b1.Property<decimal>("GeneralAvailableAmount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BudgetPressureGeneralAvailableAmount");

                            b1.Property<string>("HealthcareAuthorizationLevel")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("BudgetPressureHealthcareAuthorizationLevel");

                            b1.Property<decimal>("HealthcareAvailableAmount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BudgetPressureHealthcareAvailableAmount");

                            b1.Property<string>("InfrastructureAuthorizationLevel")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("BudgetPressureInfrastructureAuthorizationLevel");

                            b1.Property<decimal>("InfrastructureAvailableAmount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BudgetPressureInfrastructureAvailableAmount");

                            b1.Property<decimal>("MunicipalOperationsExpenses")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BudgetPressureMunicipalOperationsExpenses");

                            b1.Property<string>("OperationsAuthorizationLevel")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("BudgetPressureOperationsAuthorizationLevel");

                            b1.Property<decimal>("OperationsAvailableAmount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("BudgetPressureOperationsAvailableAmount");

                            b1.Property<decimal>("PressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("BudgetPressureIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityPowerDistributionInfrastructureState", "PowerDistributionInfrastructure", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("CrewReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("PowerDistributionCrewReadinessIndex");

                            b1.Property<bool>("EmergencyModeEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("PowerDistributionEmergencyModeEnabled");

                            b1.Property<decimal>("GridIntegrityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("PowerDistributionGridIntegrityIndex");

                            b1.Property<decimal>("IncidentPressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("PowerDistributionIncidentPressureIndex");

                            b1.Property<decimal>("SubstationCapacityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("PowerDistributionSubstationCapacityIndex");

                            b1.Property<decimal>("SwitchingReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("PowerDistributionSwitchingReadinessIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityResourceSupplyState", "ResourceSupply", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("EffectiveAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ResourceEffectiveAtUtc");

                            b1.Property<long>("EffectiveTickId")
                                .HasColumnType("bigint")
                                .HasColumnName("ResourceEffectiveTickId");

                            b1.Property<decimal>("EmergencyWaterResupplyReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("ResourceEmergencyWaterResupplyReadinessIndex");

                            b1.Property<decimal>("EmergencyWaterShortageRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("ResourceEmergencyWaterShortageRiskIndex");

                            b1.Property<decimal>("EmergencyWaterStockLevelIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("ResourceEmergencyWaterStockLevelIndex");

                            b1.Property<decimal>("FiltersResupplyReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("ResourceFiltersResupplyReadinessIndex");

                            b1.Property<decimal>("FiltersShortageRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("ResourceFiltersShortageRiskIndex");

                            b1.Property<decimal>("FiltersStockLevelIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("ResourceFiltersStockLevelIndex");

                            b1.Property<decimal>("FuelResupplyReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("ResourceFuelResupplyReadinessIndex");

                            b1.Property<decimal>("FuelShortageRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("ResourceFuelShortageRiskIndex");

                            b1.Property<decimal>("FuelStockLevelIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("ResourceFuelStockLevelIndex");

                            b1.Property<decimal>("SparePartsResupplyReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("ResourceSparePartsResupplyReadinessIndex");

                            b1.Property<decimal>("SparePartsShortageRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("ResourceSparePartsShortageRiskIndex");

                            b1.Property<decimal>("SparePartsStockLevelIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("ResourceSparePartsStockLevelIndex");

                            b1.Property<decimal>("SupplyStressIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("ResourceSupplyStressIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityRoadAccessInfrastructureState", "RoadAccessInfrastructure", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("CorridorAvailabilityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("RoadAccessCorridorAvailabilityIndex");

                            b1.Property<decimal>("CrewReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("RoadAccessCrewReadinessIndex");

                            b1.Property<bool>("EmergencyModeEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("RoadAccessEmergencyModeEnabled");

                            b1.Property<decimal>("IncidentPressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("RoadAccessIncidentPressureIndex");

                            b1.Property<decimal>("SurfaceIntegrityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("RoadAccessSurfaceIntegrityIndex");

                            b1.Property<decimal>("TrafficControlReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("RoadAccessTrafficControlReadinessIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CitySanitationInfrastructureState", "SanitationInfrastructure", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("CrewReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SanitationCrewReadinessIndex");

                            b1.Property<bool>("EmergencyModeEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("SanitationEmergencyModeEnabled");

                            b1.Property<decimal>("IncidentPressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SanitationIncidentPressureIndex");

                            b1.Property<decimal>("NetworkIntegrityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SanitationNetworkIntegrityIndex");

                            b1.Property<decimal>("OverflowControlIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SanitationOverflowControlIndex");

                            b1.Property<decimal>("TreatmentStabilityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SanitationTreatmentStabilityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CitySnowRemovalInfrastructureState", "SnowRemovalInfrastructure", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("CrewReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SnowRemovalCrewReadinessIndex");

                            b1.Property<decimal>("DeicingReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SnowRemovalDeicingReadinessIndex");

                            b1.Property<bool>("EmergencyModeEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("SnowRemovalEmergencyModeEnabled");

                            b1.Property<decimal>("FleetAvailabilityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SnowRemovalFleetAvailabilityIndex");

                            b1.Property<decimal>("IncidentPressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SnowRemovalIncidentPressureIndex");

                            b1.Property<decimal>("RouteCoverageIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SnowRemovalRouteCoverageIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityUtilityIncidentInfrastructureState", "UtilityIncidentInfrastructure", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("DispatchReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("UtilityIncidentsDispatchReadinessIndex");

                            b1.Property<bool>("EmergencyModeEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("UtilityIncidentsEmergencyModeEnabled");

                            b1.Property<decimal>("FieldCoordinationIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("UtilityIncidentsFieldCoordinationIndex");

                            b1.Property<decimal>("IncidentQueuePressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("UtilityIncidentsIncidentQueuePressureIndex");

                            b1.Property<decimal>("RestorationCoverageIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("UtilityIncidentsRestorationCoverageIndex");

                            b1.Property<decimal>("SpareCapacityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("UtilityIncidentsSpareCapacityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.OwnsOne("Matrix.SimulationSystems.Domain.Scenarios.ClassicCity.Systems.CityWaterDistributionInfrastructureState", "WaterDistributionInfrastructure", b1 =>
                        {
                            b1.Property<Guid>("CityEnvironmentalConditionStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("CrewReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WaterDistributionCrewReadinessIndex");

                            b1.Property<bool>("EmergencyModeEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("WaterDistributionEmergencyModeEnabled");

                            b1.Property<decimal>("IncidentPressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WaterDistributionIncidentPressureIndex");

                            b1.Property<decimal>("NetworkIntegrityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WaterDistributionNetworkIntegrityIndex");

                            b1.Property<decimal>("PumpReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WaterDistributionPumpReadinessIndex");

                            b1.Property<decimal>("TreatmentCapacityIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("WaterDistributionTreatmentCapacityIndex");

                            b1.HasKey("CityEnvironmentalConditionStateId");

                            b1.ToTable("CityEnvironmentalConditions");

                            b1.WithOwner()
                                .HasForeignKey("CityEnvironmentalConditionStateId");
                        });

                    b.Navigation("Drainage")
                        .IsRequired();

                    b.Navigation("DrainageInfrastructure")
                        .IsRequired();

                    b.Navigation("Heating")
                        .IsRequired();

                    b.Navigation("HeatingInfrastructure")
                        .IsRequired();

                    b.Navigation("OperationalBudgetPressure")
                        .IsRequired();

                    b.Navigation("PendingDrainageMaintenance")
                        .IsRequired();

                    b.Navigation("PendingHeatingMaintenance")
                        .IsRequired();

                    b.Navigation("PendingPowerDistributionMaintenance")
                        .IsRequired();

                    b.Navigation("PendingRoadAccessMaintenance")
                        .IsRequired();

                    b.Navigation("PendingSanitationMaintenance")
                        .IsRequired();

                    b.Navigation("PendingSnowRemovalMaintenance")
                        .IsRequired();

                    b.Navigation("PendingUtilityIncidentResponse")
                        .IsRequired();

                    b.Navigation("PendingWaterDistributionMaintenance")
                        .IsRequired();

                    b.Navigation("PowerDistribution")
                        .IsRequired();

                    b.Navigation("PowerDistributionInfrastructure")
                        .IsRequired();

                    b.Navigation("ResourceSupply")
                        .IsRequired();

                    b.Navigation("RoadAccess")
                        .IsRequired();

                    b.Navigation("RoadAccessInfrastructure")
                        .IsRequired();

                    b.Navigation("Sanitation")
                        .IsRequired();

                    b.Navigation("SanitationInfrastructure")
                        .IsRequired();

                    b.Navigation("SnowRemoval")
                        .IsRequired();

                    b.Navigation("SnowRemovalInfrastructure")
                        .IsRequired();

                    b.Navigation("UtilityIncidentInfrastructure")
                        .IsRequired();

                    b.Navigation("UtilityIncidents")
                        .IsRequired();

                    b.Navigation("WaterDistribution")
                        .IsRequired();

                    b.Navigation("WaterDistributionInfrastructure")
                        .IsRequired();

                    b.Navigation("WeatherPressure")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
