// <auto-generated />
using System;
using Matrix.Healthcare.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.Healthcare.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HealthcareDbContext))]
    [Migration("20260705130800_AddCareOperationalState")]
    partial class AddCareOperationalState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.BuildingBlocks.Infrastructure.Outbox.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAttemptOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextAttemptOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "LockedUntilUtc", "NextAttemptOnUtc", "OccurredOnUtc")
                        .HasFilter("\"ProcessedOnUtc\" IS NULL");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Matrix.Healthcare.Domain.Care.PatientCareAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_care_assignment_id");

                    b.Property<long>("AssessmentRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("assessment_revision");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<int?>("CancellationReason")
                        .HasColumnType("integer")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateOnly>("CareDate")
                        .HasColumnType("date")
                        .HasColumnName("care_date");

                    b.Property<Guid>("CareFacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_facility_id");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date")
                        .HasColumnName("closed_on");

                    b.Property<long>("LifecycleRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("lifecycle_revision");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<int?>("TreatmentHealthDelta")
                        .HasColumnType("integer")
                        .HasColumnName("treatment_health_delta");

                    b.Property<bool?>("TreatmentMedicalStateChanged")
                        .HasColumnType("boolean")
                        .HasColumnName("treatment_medical_state_changed");

                    b.Property<int>("Urgency")
                        .HasColumnType("integer")
                        .HasColumnName("urgency");

                    b.HasKey("Id");

                    b.HasIndex("CareFacilityId");

                    b.HasIndex("SimulationHostId", "CareDate", "CareFacilityId")
                        .HasDatabaseName("ix_healthcare_patient_care_assignments_capacity_usage");

                    b.HasIndex("SimulationHostId", "PatientId", "CareDate")
                        .IsUnique()
                        .HasDatabaseName("ux_healthcare_patient_care_assignments_patient_date");

                    b.HasIndex("SimulationHostId", "Status", "PatientId", "CareDate")
                        .HasDatabaseName("ix_healthcare_patient_care_assignments_due_lookup");

                    b.ToTable("healthcare_patient_care_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_healthcare_patient_care_assignments_assessment_revision", "assessment_revision >= 0");

                            t.HasCheckConstraint("ck_healthcare_patient_care_assignments_cancellation_reason", "cancellation_reason IS NULL OR cancellation_reason BETWEEN 0 AND 4");

                            t.HasCheckConstraint("ck_healthcare_patient_care_assignments_closure", "(status = 0 AND closed_on IS NULL AND closed_at_utc IS NULL AND cancellation_reason IS NULL AND treatment_health_delta IS NULL AND treatment_medical_state_changed IS NULL) OR (status = 1 AND closed_on IS NOT NULL AND closed_at_utc IS NOT NULL AND cancellation_reason IS NULL AND treatment_health_delta IS NOT NULL AND treatment_medical_state_changed IS NOT NULL) OR (status = 2 AND closed_on IS NOT NULL AND closed_at_utc IS NOT NULL AND cancellation_reason IS NOT NULL AND treatment_health_delta IS NULL AND treatment_medical_state_changed IS NULL)");

                            t.HasCheckConstraint("ck_healthcare_patient_care_assignments_lifecycle_revision", "lifecycle_revision >= 0");

                            t.HasCheckConstraint("ck_healthcare_patient_care_assignments_status", "status BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Matrix.Healthcare.Domain.Care.PatientCareNeed", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastAssessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_assessed_at_utc");

                    b.Property<long>("LastAssessmentRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("last_assessment_revision");

                    b.Property<long>("LastLifecycleRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("last_lifecycle_revision");

                    b.Property<DateOnly>("RequestedOn")
                        .HasColumnType("date")
                        .HasColumnName("requested_on");

                    b.Property<DateOnly?>("ResolvedOn")
                        .HasColumnType("date")
                        .HasColumnName("resolved_on");

                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.Property<int>("Urgency")
                        .HasColumnType("integer")
                        .HasColumnName("urgency");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SimulationHostId", "IsActive", "Urgency", "RequestedOn")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("ix_healthcare_patient_care_needs_allocation_candidates");

                    b.ToTable("healthcare_patient_care_needs", (string)null);
                });

            modelBuilder.Entity("Matrix.Healthcare.Domain.Facilities.CareFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("care_facility_id");

                    b.Property<int>("DailyPatientCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("daily_patient_capacity");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<long>("LastSourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("last_source_revision");

                    b.Property<DateTimeOffset>("LastSynchronizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synchronized_at_utc");

                    b.Property<Guid?>("LocationAnchorId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_anchor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SimulationHostId", "IsActive", "Kind")
                        .HasDatabaseName("ix_healthcare_care_facilities_capacity_candidates");

                    b.ToTable("healthcare_care_facilities", null, t =>
                        {
                            t.HasCheckConstraint("ck_healthcare_care_facilities_daily_capacity_positive", "daily_patient_capacity > 0");
                        });
                });

            modelBuilder.Entity("Matrix.Healthcare.Domain.Operations.CareMedicineSupplyState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.Property<DateTimeOffset>("LastObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at_utc");

                    b.Property<long>("LastSourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("last_source_revision");

                    b.Property<decimal>("ShortageRisk")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("shortage_risk_index");

                    b.Property<decimal>("StockLevel")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("stock_level_index");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("healthcare_care_medicine_supply_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_healthcare_care_medicine_shortage_risk", "shortage_risk_index BETWEEN 0 AND 1");

                            t.HasCheckConstraint("ck_healthcare_care_medicine_source_revision", "last_source_revision >= 0");

                            t.HasCheckConstraint("ck_healthcare_care_medicine_stock_level", "stock_level_index BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Matrix.Healthcare.Domain.Operations.CareServiceQualityState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.Property<DateTimeOffset>("LastObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at_utc");

                    b.Property<decimal>("QualityMultiplier")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("quality_multiplier");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("healthcare_care_service_quality_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_healthcare_care_service_quality_multiplier", "quality_multiplier BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Matrix.Healthcare.Domain.Patients.PatientMedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health_score");

                    b.Property<long>("LastLifecycleRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_lifecycle_revision");

                    b.Property<long>("LastProgressionRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(-1L)
                        .HasColumnName("last_progression_revision");

                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.HasKey("Id");

                    b.HasIndex("SimulationHostId")
                        .HasDatabaseName("ix_healthcare_medical_records_simulation_host");

                    b.ToTable("healthcare_patient_medical_records", (string)null);
                });

            modelBuilder.Entity("Matrix.Healthcare.Domain.Patients.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_alive");

                    b.Property<long>("LastLifecycleRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_lifecycle_revision");

                    b.Property<long>("LastSourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("last_source_revision");

                    b.Property<DateTimeOffset>("LastSynchronizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synchronized_at_utc");

                    b.Property<int>("Sex")
                        .HasColumnType("integer")
                        .HasColumnName("sex");

                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.HasKey("Id");

                    b.HasIndex("SimulationHostId", "IsActive", "IsAlive", "BirthDate")
                        .HasDatabaseName("ix_healthcare_profiles_tick_candidates");

                    b.ToTable("healthcare_patient_profiles", (string)null);
                });

            modelBuilder.Entity("Matrix.Healthcare.Domain.Progression.PatientHealthProgressionBatchSet", b =>
                {
                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("FirstReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_received_at_utc");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_complete");

                    b.Property<DateTimeOffset>("LastReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_received_at_utc");

                    b.Property<int>("ReceivedBatchCount")
                        .HasColumnType("integer")
                        .HasColumnName("received_batch_count");

                    b.Property<int>("TotalBatches")
                        .HasColumnType("integer")
                        .HasColumnName("total_batches");

                    b.Property<byte[]>("_receivedBatchMap")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("received_batch_map");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("SimulationHostId", "SourceRevision");

                    b.ToTable("healthcare_patient_health_progression_batch_sets", (string)null);
                });

            modelBuilder.Entity("Matrix.Healthcare.Infrastructure.Persistence.Models.HealthcareSimulationDeletionState", b =>
                {
                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.Property<DateTimeOffset>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("SimulationHostId");

                    b.ToTable("healthcare_simulation_deletions", (string)null);
                });

            modelBuilder.Entity("Matrix.Healthcare.Domain.Care.PatientCareAssignment", b =>
                {
                    b.HasOne("Matrix.Healthcare.Domain.Facilities.CareFacility", null)
                        .WithMany()
                        .HasForeignKey("CareFacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Matrix.Healthcare.Domain.Patients.PatientMedicalRecord", b =>
                {
                    b.OwnsOne("Matrix.Healthcare.Domain.Patients.PatientIllnessState", "Illness", b1 =>
                        {
                            b1.Property<Guid>("PatientMedicalRecordId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("CurrentKind")
                                .HasColumnType("integer")
                                .HasColumnName("illness_kind");

                            b1.Property<int?>("CurrentSeverity")
                                .HasColumnType("integer")
                                .HasColumnName("illness_severity");

                            b1.Property<DateOnly?>("DiagnosedOn")
                                .HasColumnType("date")
                                .HasColumnName("illness_diagnosed_on");

                            b1.Property<DateOnly?>("LastRecoveredOn")
                                .HasColumnType("date")
                                .HasColumnName("last_illness_recovered_on");

                            b1.HasKey("PatientMedicalRecordId");

                            b1.ToTable("healthcare_patient_medical_records");

                            b1.WithOwner()
                                .HasForeignKey("PatientMedicalRecordId");
                        });

                    b.Navigation("Illness")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
