// <auto-generated />
using System;
using Matrix.Healthcare.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.Healthcare.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HealthcareDbContext))]
    [Migration("20260627051600_AddHealthcareSimulationDeletionState")]
    partial class AddHealthcareSimulationDeletionState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.Healthcare.Domain.Patients.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_alive");

                    b.Property<long>("LastSourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("last_source_revision");

                    b.Property<DateTimeOffset>("LastSynchronizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synchronized_at_utc");

                    b.Property<int>("Sex")
                        .HasColumnType("integer")
                        .HasColumnName("sex");

                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.HasKey("Id");

                    b.HasIndex("SimulationHostId", "IsActive", "IsAlive", "BirthDate")
                        .HasDatabaseName("ix_healthcare_profiles_tick_candidates");

                    b.ToTable("healthcare_patient_profiles", (string)null);
                });

            modelBuilder.Entity("Matrix.Healthcare.Infrastructure.Persistence.Models.HealthcareSimulationDeletionState", b =>
                {
                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.Property<DateTimeOffset>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("SimulationHostId");

                    b.ToTable("healthcare_simulation_deletions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
