// <auto-generated />
using System;
using Matrix.Healthcare.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.Healthcare.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HealthcareDbContext))]
    [Migration("20260628105300_AddMedicalProgressionRevision")]
    partial class AddMedicalProgressionRevision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.Healthcare.Domain.Patients.PatientMedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health_score");

                    b.Property<long>("LastProgressionRevision")
                        .HasColumnType("bigint")
                        .HasDefaultValue(-1L)
                        .HasColumnName("last_progression_revision");

                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.HasKey("Id");

                    b.HasIndex("SimulationHostId")
                        .HasDatabaseName("ix_healthcare_medical_records_simulation_host");

                    b.ToTable("healthcare_patient_medical_records", (string)null);
                });

            modelBuilder.Entity("Matrix.Healthcare.Domain.Patients.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_alive");

                    b.Property<long>("LastSourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("last_source_revision");

                    b.Property<DateTimeOffset>("LastSynchronizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synchronized_at_utc");

                    b.Property<int>("Sex")
                        .HasColumnType("integer")
                        .HasColumnName("sex");

                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.HasKey("Id");

                    b.HasIndex("SimulationHostId", "IsActive", "IsAlive", "BirthDate")
                        .HasDatabaseName("ix_healthcare_profiles_tick_candidates");

                    b.ToTable("healthcare_patient_profiles", (string)null);
                });

            modelBuilder.Entity("Matrix.Healthcare.Infrastructure.Persistence.Models.HealthcareSimulationDeletionState", b =>
                {
                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.Property<DateTimeOffset>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("SimulationHostId");

                    b.ToTable("healthcare_simulation_deletions", (string)null);
                });

            modelBuilder.Entity("Matrix.Healthcare.Domain.Patients.PatientMedicalRecord", b =>
                {
                    b.OwnsOne("Matrix.Healthcare.Domain.Patients.PatientIllnessState", "Illness", b1 =>
                        {
                            b1.Property<Guid>("PatientMedicalRecordId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("CurrentKind")
                                .HasColumnType("integer")
                                .HasColumnName("illness_kind");

                            b1.Property<int?>("CurrentSeverity")
                                .HasColumnType("integer")
                                .HasColumnName("illness_severity");

                            b1.Property<DateOnly?>("DiagnosedOn")
                                .HasColumnType("date")
                                .HasColumnName("illness_diagnosed_on");

                            b1.Property<DateOnly?>("LastRecoveredOn")
                                .HasColumnType("date")
                                .HasColumnName("last_illness_recovered_on");

                            b1.HasKey("PatientMedicalRecordId");

                            b1.ToTable("healthcare_patient_medical_records");

                            b1.WithOwner()
                                .HasForeignKey("PatientMedicalRecordId");
                        });

                    b.Navigation("Illness")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
