<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Matrix.PermissionCatalog.Abstractions\Matrix.PermissionCatalog.Abstractions.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Self\Sessions\Requests\"/>
  </ItemGroup>

</Project>