// <auto-generated />
using System;
using Matrix.Economy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.Economy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EconomyDbContext))]
    [Migration("20260328223759_AddCityHouseholdAccounts")]
    partial class AddCityHouseholdAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.Economy.Domain.Aggregates.CityBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance_amount");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<decimal>("TotalCityExpenses")
                        .HasColumnType("numeric")
                        .HasColumnName("total_city_expenses_amount");

                    b.Property<decimal>("TotalDirectRevenue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_direct_revenue_amount");

                    b.Property<decimal>("TotalGrossPayroll")
                        .HasColumnType("numeric")
                        .HasColumnName("total_gross_payroll_amount");

                    b.Property<decimal>("TotalIncomeTaxIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("total_income_tax_income_amount");

                    b.Property<decimal>("TotalNetPayroll")
                        .HasColumnType("numeric")
                        .HasColumnName("total_net_payroll_amount");

                    b.Property<decimal>("TotalRetailTurnover")
                        .HasColumnType("numeric")
                        .HasColumnName("total_retail_turnover_amount");

                    b.Property<decimal>("TotalSalesTaxIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("total_sales_tax_income_amount");

                    b.Property<decimal>("TotalTaxIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("total_tax_income_amount");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_display_name");

                    b.Property<string>("UnitKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_kind");

                    b.Property<string>("UnitSymbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_symbol");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.ToTable("City_Budget", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Aggregates.CityBusiness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance_amount");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("TaxReserve")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_reserve_amount");

                    b.Property<decimal>("TotalCapitalInjections")
                        .HasColumnType("numeric")
                        .HasColumnName("total_capital_injections_amount");

                    b.Property<decimal>("TotalNetSalesRevenue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_net_sales_revenue_amount");

                    b.Property<decimal>("TotalOperatingExpenses")
                        .HasColumnType("numeric")
                        .HasColumnName("total_operating_expenses_amount");

                    b.Property<decimal>("TotalRetailTurnover")
                        .HasColumnType("numeric")
                        .HasColumnName("total_retail_turnover_amount");

                    b.Property<decimal>("TotalTaxRemitted")
                        .HasColumnType("numeric")
                        .HasColumnName("total_tax_remitted_amount");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_display_name");

                    b.Property<string>("UnitKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_kind");

                    b.Property<string>("UnitSymbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_symbol");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CityId", "Name")
                        .IsUnique();

                    b.ToTable("City_Business", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Entities.CityBudgetLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("text")
                        .HasColumnName("reference_code");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceCode");

                    b.HasIndex("CityId", "OccurredAtUtc");

                    b.ToTable("City_Budget_Ledger_Entries", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Entities.CityBudgetSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateOnly>("CurrentDate")
                        .HasColumnType("date")
                        .HasColumnName("current_date");

                    b.Property<decimal>("GrossPayroll")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_payroll_amount");

                    b.Property<int>("HouseholdCount")
                        .HasColumnType("integer")
                        .HasColumnName("household_count");

                    b.Property<decimal>("HousingSpend")
                        .HasColumnType("numeric")
                        .HasColumnName("housing_spend_amount");

                    b.Property<decimal>("IncomeTax")
                        .HasColumnType("numeric")
                        .HasColumnName("income_tax_amount");

                    b.Property<decimal>("NetPayroll")
                        .HasColumnType("numeric")
                        .HasColumnName("net_payroll_amount");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<int>("ResidentCount")
                        .HasColumnType("integer")
                        .HasColumnName("resident_count");

                    b.Property<decimal>("RetailTax")
                        .HasColumnType("numeric")
                        .HasColumnName("retail_tax_amount");

                    b.Property<decimal>("RetailTurnover")
                        .HasColumnType("numeric")
                        .HasColumnName("retail_turnover_amount");

                    b.Property<int>("SettledDays")
                        .HasColumnType("integer")
                        .HasColumnName("settled_days");

                    b.Property<long>("TickId")
                        .HasColumnType("bigint")
                        .HasColumnName("tick_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("CityId", "TickId")
                        .IsUnique();

                    b.ToTable("City_Budget_Settlements", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Entities.CityBusinessLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("text")
                        .HasColumnName("reference_code");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_amount");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("BusinessId", "OccurredAtUtc");

                    b.ToTable("City_Business_Ledger_Entry", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
