// <auto-generated />
using System;
using Matrix.Economy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.Economy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EconomyDbContext))]
    [Migration("20260414045346_AddCityEconomyProgressionState")]
    partial class AddCityEconomyProgressionState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.Economy.Domain.Aggregates.CityBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance_amount");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<decimal>("TotalCityExpenses")
                        .HasColumnType("numeric")
                        .HasColumnName("total_city_expenses_amount");

                    b.Property<decimal>("TotalDirectRevenue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_direct_revenue_amount");

                    b.Property<decimal>("TotalGrossPayroll")
                        .HasColumnType("numeric")
                        .HasColumnName("total_gross_payroll_amount");

                    b.Property<decimal>("TotalIncomeTaxIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("total_income_tax_income_amount");

                    b.Property<decimal>("TotalNetPayroll")
                        .HasColumnType("numeric")
                        .HasColumnName("total_net_payroll_amount");

                    b.Property<decimal>("TotalRetailTurnover")
                        .HasColumnType("numeric")
                        .HasColumnName("total_retail_turnover_amount");

                    b.Property<decimal>("TotalSalesTaxIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("total_sales_tax_income_amount");

                    b.Property<decimal>("TotalTaxIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("total_tax_income_amount");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_display_name");

                    b.Property<string>("UnitKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_kind");

                    b.Property<string>("UnitSymbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_symbol");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.ToTable("City_Budget", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Aggregates.CityBusiness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance_amount");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalReferenceCode")
                        .HasColumnType("text")
                        .HasColumnName("external_reference_code");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("TaxReserve")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_reserve_amount");

                    b.Property<string>("TemplateKey")
                        .HasColumnType("text")
                        .HasColumnName("template_key");

                    b.Property<decimal>("TotalCapitalInjections")
                        .HasColumnType("numeric")
                        .HasColumnName("total_capital_injections_amount");

                    b.Property<decimal>("TotalNetSalesRevenue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_net_sales_revenue_amount");

                    b.Property<decimal>("TotalOperatingExpenses")
                        .HasColumnType("numeric")
                        .HasColumnName("total_operating_expenses_amount");

                    b.Property<decimal>("TotalRetailTurnover")
                        .HasColumnType("numeric")
                        .HasColumnName("total_retail_turnover_amount");

                    b.Property<decimal>("TotalTaxRemitted")
                        .HasColumnType("numeric")
                        .HasColumnName("total_tax_remitted_amount");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_display_name");

                    b.Property<string>("UnitKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_kind");

                    b.Property<string>("UnitSymbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_symbol");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CityId", "ExternalReferenceCode")
                        .IsUnique()
                        .HasFilter("\"external_reference_code\" IS NOT NULL");

                    b.HasIndex("CityId", "Name")
                        .IsUnique();

                    b.HasIndex("CityId", "TemplateKey")
                        .IsUnique()
                        .HasFilter("\"template_key\" IS NOT NULL");

                    b.ToTable("City_Business", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Aggregates.CityHouseholdAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance_amount");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalReferenceCode")
                        .HasColumnType("text")
                        .HasColumnName("external_reference_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("TotalConsumerSpending")
                        .HasColumnType("numeric")
                        .HasColumnName("total_consumer_spending_amount");

                    b.Property<decimal>("TotalOpeningBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("total_opening_balance_amount");

                    b.Property<decimal>("TotalPayrollIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("total_payroll_income_amount");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_display_name");

                    b.Property<string>("UnitKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_kind");

                    b.Property<string>("UnitSymbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_symbol");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ExternalReferenceCode");

                    b.HasIndex("CityId", "ExternalReferenceCode")
                        .IsUnique()
                        .HasFilter("\"external_reference_code\" IS NOT NULL");

                    b.HasIndex("CityId", "Name")
                        .IsUnique();

                    b.ToTable("City_Household_Account", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Aggregates.CityHouseholdObligation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingCadence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billing_cadence");

                    b.Property<decimal>("ChargeAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("charge_amount");

                    b.Property<int>("ChargeCount")
                        .HasColumnType("integer")
                        .HasColumnName("charge_count");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("HouseholdAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_account_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastChargedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_charged_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("NextChargeDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_charge_due_at_utc");

                    b.Property<Guid>("ProviderBusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_business_id");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_amount");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_display_name");

                    b.Property<string>("UnitKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_kind");

                    b.Property<string>("UnitSymbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_symbol");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("HouseholdAccountId");

                    b.HasIndex("ProviderBusinessId");

                    b.HasIndex("CityId", "NextChargeDueAtUtc");

                    b.HasIndex("HouseholdAccountId", "ProviderBusinessId", "Name")
                        .IsUnique();

                    b.ToTable("City_Household_Obligation", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Entities.CityBudgetAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("target_amount");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("numeric")
                        .HasColumnName("total_spent_amount");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_display_name");

                    b.Property<string>("UnitKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_kind");

                    b.Property<string>("UnitSymbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_symbol");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CityId", "Category")
                        .IsUnique();

                    b.ToTable("City_Budget_Allocation", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Entities.CityBudgetLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("text")
                        .HasColumnName("reference_code");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceCode");

                    b.HasIndex("CityId", "OccurredAtUtc");

                    b.ToTable("City_Budget_Ledger_Entries", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Entities.CityBudgetSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateOnly>("CurrentDate")
                        .HasColumnType("date")
                        .HasColumnName("current_date");

                    b.Property<decimal>("GrossPayroll")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_payroll_amount");

                    b.Property<int>("HouseholdCount")
                        .HasColumnType("integer")
                        .HasColumnName("household_count");

                    b.Property<decimal>("HousingSpend")
                        .HasColumnType("numeric")
                        .HasColumnName("housing_spend_amount");

                    b.Property<decimal>("IncomeTax")
                        .HasColumnType("numeric")
                        .HasColumnName("income_tax_amount");

                    b.Property<decimal>("NetPayroll")
                        .HasColumnType("numeric")
                        .HasColumnName("net_payroll_amount");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<int>("ResidentCount")
                        .HasColumnType("integer")
                        .HasColumnName("resident_count");

                    b.Property<decimal>("RetailTax")
                        .HasColumnType("numeric")
                        .HasColumnName("retail_tax_amount");

                    b.Property<decimal>("RetailTurnover")
                        .HasColumnType("numeric")
                        .HasColumnName("retail_turnover_amount");

                    b.Property<int>("SettledDays")
                        .HasColumnType("integer")
                        .HasColumnName("settled_days");

                    b.Property<long>("TickId")
                        .HasColumnType("bigint")
                        .HasColumnName("tick_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("CityId", "TickId")
                        .IsUnique();

                    b.ToTable("City_Budget_Settlements", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Entities.CityBusinessLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("text")
                        .HasColumnName("reference_code");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("tax_amount");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("BusinessId", "OccurredAtUtc");

                    b.HasIndex("BusinessId", "Kind", "ReferenceCode")
                        .IsUnique()
                        .HasFilter("\"reference_code\" IS NOT NULL");

                    b.ToTable("City_Business_Ledger_Entry", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Entities.CityEconomyProgressionState", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<long>("LastCompletedTickId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_completed_tick_id");

                    b.Property<DateTime>("LastProcessedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_processed_date");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("CityId");

                    b.ToTable("CityEconomyProgressionStates", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Entities.CityHouseholdAccountLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("HouseholdAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_account_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("text")
                        .HasColumnName("reference_code");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("HouseholdAccountId", "OccurredAtUtc");

                    b.HasIndex("HouseholdAccountId", "Kind", "ReferenceCode")
                        .IsUnique()
                        .HasFilter("\"reference_code\" IS NOT NULL");

                    b.ToTable("City_Household_Account_Ledger_Entry", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
