// <auto-generated />
using System;
using Matrix.Economy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.Economy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EconomyDbContext))]
    [Migration("20260328181101_AddCityBudgetOperatingExpenses")]
    partial class AddCityBudgetOperatingExpenses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.Economy.Domain.Aggregates.CityBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance_amount");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<decimal>("TotalCityExpenses")
                        .HasColumnType("numeric")
                        .HasColumnName("total_city_expenses_amount");

                    b.Property<decimal>("TotalGrossPayroll")
                        .HasColumnType("numeric")
                        .HasColumnName("total_gross_payroll_amount");

                    b.Property<decimal>("TotalIncomeTaxIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("total_income_tax_income_amount");

                    b.Property<decimal>("TotalNetPayroll")
                        .HasColumnType("numeric")
                        .HasColumnName("total_net_payroll_amount");

                    b.Property<decimal>("TotalRetailTurnover")
                        .HasColumnType("numeric")
                        .HasColumnName("total_retail_turnover_amount");

                    b.Property<decimal>("TotalSalesTaxIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("total_sales_tax_income_amount");

                    b.Property<decimal>("TotalTaxIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("total_tax_income_amount");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.ToTable("City_Budget", (string)null);
                });

            modelBuilder.Entity("Matrix.Economy.Domain.Entities.CityBudgetSettlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateOnly>("CurrentDate")
                        .HasColumnType("date")
                        .HasColumnName("current_date");

                    b.Property<decimal>("GrossPayroll")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_payroll_amount");

                    b.Property<int>("HouseholdCount")
                        .HasColumnType("integer")
                        .HasColumnName("household_count");

                    b.Property<decimal>("HousingSpend")
                        .HasColumnType("numeric")
                        .HasColumnName("housing_spend_amount");

                    b.Property<decimal>("IncomeTax")
                        .HasColumnType("numeric")
                        .HasColumnName("income_tax_amount");

                    b.Property<decimal>("NetPayroll")
                        .HasColumnType("numeric")
                        .HasColumnName("net_payroll_amount");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<int>("ResidentCount")
                        .HasColumnType("integer")
                        .HasColumnName("resident_count");

                    b.Property<decimal>("RetailTax")
                        .HasColumnType("numeric")
                        .HasColumnName("retail_tax_amount");

                    b.Property<decimal>("RetailTurnover")
                        .HasColumnType("numeric")
                        .HasColumnName("retail_turnover_amount");

                    b.Property<int>("SettledDays")
                        .HasColumnType("integer")
                        .HasColumnName("settled_days");

                    b.Property<long>("TickId")
                        .HasColumnType("bigint")
                        .HasColumnName("tick_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("CityId", "TickId")
                        .IsUnique();

                    b.ToTable("City_Budget_Settlements", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
