// <auto-generated />
using System;
using Matrix.Education.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.Education.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    [Migration("20260714081300_ScopeEducationEnrollmentReferences")]
    partial class ScopeEducationEnrollmentReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.Education.Domain.Enrollments.StudentEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<DateTime?>("ClosedOn")
                        .HasColumnType("date")
                        .HasColumnName("closed_on");

                    b.Property<DateTime>("EnrolledOn")
                        .HasColumnType("date")
                        .HasColumnName("enrolled_on");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId", "Status")
                        .HasDatabaseName("ix_education_enrollments_institution_status");

                    b.HasIndex("SimulationHostId", "InstitutionId");

                    b.HasIndex("SimulationHostId", "ResidentId")
                        .IsUnique()
                        .HasDatabaseName("ux_education_enrollments_active_resident")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("SimulationHostId", "Status", "Stage", "ResidentId")
                        .HasDatabaseName("ix_education_enrollments_tick_candidates");

                    b.ToTable("education_enrollments", null, t =>
                        {
                            t.HasCheckConstraint("ck_education_enrollments_terminal_date", "(status = 'Active' AND closed_on IS NULL) OR (status <> 'Active' AND closed_on IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Matrix.Education.Domain.Institutions.EducationInstitution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("institution_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("CurrentEnrollmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("current_enrollment_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<long>("LastSourceRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(-1L)
                        .HasColumnName("last_source_revision");

                    b.Property<DateTimeOffset?>("LastSynchronizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synchronized_at_utc");

                    b.Property<Guid?>("LocationAnchorId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_anchor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SimulationHostId", "IsActive", "Kind")
                        .HasDatabaseName("ix_education_institutions_capacity_candidates");

                    b.ToTable("education_institutions", null, t =>
                        {
                            t.HasCheckConstraint("ck_education_institutions_capacity_positive", "capacity > 0");

                            t.HasCheckConstraint("ck_education_institutions_enrollment_within_capacity", "current_enrollment_count >= 0 AND current_enrollment_count <= capacity");
                        });
                });

            modelBuilder.Entity("Matrix.Education.Domain.Progression.EducationProgressionCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.Property<DateTimeOffset>("LastCompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_completed_at_utc");

                    b.Property<long>("LastCompletedTickId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_completed_tick_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("education_progression_checkpoints", null, t =>
                        {
                            t.HasCheckConstraint("ck_education_progression_checkpoint_tick", "last_completed_tick_id >= 0");
                        });
                });

            modelBuilder.Entity("Matrix.Education.Domain.Students.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("CompletedStage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("completed_stage");

                    b.Property<DateTime?>("CompletedStageOn")
                        .HasColumnType("date")
                        .HasColumnName("completed_stage_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_alive");

                    b.Property<long>("LastLifecycleRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_lifecycle_revision");

                    b.Property<long>("LastSourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("last_source_revision");

                    b.Property<DateTimeOffset>("LastSynchronizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synchronized_at_utc");

                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.HasKey("Id");

                    b.HasIndex("SimulationHostId", "IsActive", "IsAlive", "BirthDate")
                        .HasDatabaseName("ix_education_profiles_tick_candidates");

                    b.ToTable("education_student_profiles", (string)null);
                });

            modelBuilder.Entity("Matrix.Education.Infrastructure.Persistence.Models.EducationSimulationDeletionState", b =>
                {
                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_host_id");

                    b.Property<DateTimeOffset>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("SimulationHostId");

                    b.ToTable("education_simulation_deletions", (string)null);
                });

            modelBuilder.Entity("Matrix.Education.Domain.Enrollments.StudentEnrollment", b =>
                {
                    b.HasOne("Matrix.Education.Domain.Institutions.EducationInstitution", null)
                        .WithMany()
                        .HasForeignKey("SimulationHostId", "InstitutionId")
                        .HasPrincipalKey("SimulationHostId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Matrix.Education.Domain.Students.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("SimulationHostId", "ResidentId")
                        .HasPrincipalKey("SimulationHostId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
