// <auto-generated />
using System;
using Matrix.Population.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.Population.Infrastructure.Migrations
{
    [DbContext(typeof(PopulationDbContext))]
    [Migration("20251129130009_RefactorPersonToValueObjects")]
    partial class RefactorPersonToValueObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.Population.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Happiness")
                        .HasColumnType("integer")
                        .HasColumnName("Happiness");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("WeightKg");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Entities.Person", b =>
                {
                    b.OwnsOne("Matrix.Population.Domain.ValueObjects.EducationInfo", "Education", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Level")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("EducationLevel");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("Matrix.Population.Domain.ValueObjects.EmploymentInfo", "Employment", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("EmploymentStatus");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");

                            b1.OwnsOne("Matrix.Population.Domain.ValueObjects.Job", "Job", b2 =>
                                {
                                    b2.Property<Guid>("EmploymentInfoPersonId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("JobTitle");

                                    b2.Property<Guid>("WorkplaceId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("WorkplaceId");

                                    b2.HasKey("EmploymentInfoPersonId");

                                    b2.ToTable("Persons");

                                    b2.WithOwner()
                                        .HasForeignKey("EmploymentInfoPersonId");
                                });

                            b1.Navigation("Job");
                        });

                    b.OwnsOne("Matrix.Population.Domain.ValueObjects.LifeState", "Life", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Health")
                                .HasColumnType("integer")
                                .HasColumnName("Health");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("LifeStatus");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");

                            b1.OwnsOne("Matrix.Population.Domain.ValueObjects.LifeSpan", "Span", b2 =>
                                {
                                    b2.Property<Guid>("LifeStatePersonId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("BirthDate")
                                        .HasColumnType("date")
                                        .HasColumnName("BirthDate");

                                    b2.Property<DateTime?>("DeathDate")
                                        .HasColumnType("date")
                                        .HasColumnName("DeathDate");

                                    b2.HasKey("LifeStatePersonId");

                                    b2.ToTable("Persons");

                                    b2.WithOwner()
                                        .HasForeignKey("LifeStatePersonId");
                                });

                            b1.Navigation("Span")
                                .IsRequired();
                        });

                    b.OwnsOne("Matrix.Population.Domain.ValueObjects.MaritalInfo", "Marital", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("SpouseId")
                                .HasColumnType("uuid")
                                .HasColumnName("SpouseId");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MaritalStatus");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("Matrix.Population.Domain.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("LastName");

                            b1.Property<string>("Patronymic")
                                .HasColumnType("text")
                                .HasColumnName("MiddleName");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("Matrix.Population.Domain.ValueObjects.Personality", "Personality", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Discipline")
                                .HasColumnType("integer")
                                .HasColumnName("Discipline");

                            b1.Property<int>("Optimism")
                                .HasColumnType("integer")
                                .HasColumnName("Optimism");

                            b1.Property<int>("RiskTolerance")
                                .HasColumnType("integer")
                                .HasColumnName("RiskTolerance");

                            b1.Property<int>("Sociability")
                                .HasColumnType("integer")
                                .HasColumnName("Sociability");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("Education")
                        .IsRequired();

                    b.Navigation("Employment")
                        .IsRequired();

                    b.Navigation("Life")
                        .IsRequired();

                    b.Navigation("Marital")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Personality")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
