// <auto-generated />
using System;
using Matrix.Population.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.Population.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PopulationDbContext))]
    [Migration("20260902071106_AddEducationAttendanceObservation")]
    partial class AddEducationAttendanceObservation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.BuildingBlocks.Infrastructure.Outbox.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAttemptOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextAttemptOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "LockedUntilUtc", "NextAttemptOnUtc", "OccurredOnUtc")
                        .HasFilter("\"ProcessedOnUtc\" IS NULL");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Entities.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CashReserve")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("CashReserve");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("Size");

                    b.HasKey("Id");

                    b.ToTable("Households", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Energy")
                        .HasColumnType("integer")
                        .HasColumnName("Energy");

                    b.Property<Guid?>("FatherId")
                        .HasColumnType("uuid")
                        .HasColumnName("FatherId");

                    b.Property<int>("FunctionalCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("FunctionalCapacity");

                    b.Property<int>("Happiness")
                        .HasColumnType("integer")
                        .HasColumnName("Happiness");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastChildbirthDate")
                        .HasColumnType("date")
                        .HasColumnName("LastChildbirthDate");

                    b.Property<long>("LastVitalStateRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(-1L);

                    b.Property<long>("LifecycleRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<Guid?>("MotherId")
                        .HasColumnType("uuid")
                        .HasColumnName("MotherId");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SocialNeed")
                        .HasColumnType("integer")
                        .HasColumnName("SocialNeed");

                    b.Property<int>("Stress")
                        .HasColumnType("integer")
                        .HasColumnName("Stress");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("WeightKg");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationActivityEvent", b =>
                {
                    b.Property<Guid>("ActivityEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PrimaryResidentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SecondaryResidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(640)
                        .HasColumnType("character varying(640)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.HasKey("ActivityEventId");

                    b.HasIndex("EventType");

                    b.HasIndex("CityId", "CurrentDate");

                    b.HasIndex("CityId", "OccurredAtUtc");

                    b.ToTable("CityPopulationActivityEvents", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationAnchorCatalogItem", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityAnchorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessRoadNodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PositionX")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("PositionY")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("CityId", "CityAnchorId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("CityId", "Type");

                    b.ToTable("CityPopulationAnchorCatalogItems", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationArchiveState", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CityId");

                    b.HasIndex("ArchivedAtUtc");

                    b.ToTable("CityPopulationArchiveStates", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationCostOfLivingState", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AffordabilityIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("CostOfLivingIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("HousingCostMultiplier")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTimeOffset>("LastEvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RetailPriceMultiplier")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UtilityCostMultiplier")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("WageMultiplier")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.HasKey("CityId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CityPopulationCostOfLivingStates", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationDailySummarySnapshot", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<int>("ActiveIllnessCount")
                        .HasColumnType("integer");

                    b.Property<int>("AdultCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AverageEnergy")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("AverageHappiness")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("AverageHealth")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("AverageSocialNeed")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("AverageStress")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ChildCount")
                        .HasColumnType("integer");

                    b.Property<int>("DeceasedCount")
                        .HasColumnType("integer");

                    b.Property<int>("EmployedCount")
                        .HasColumnType("integer");

                    b.Property<int>("HomelessHouseholdCount")
                        .HasColumnType("integer");

                    b.Property<int>("HomelessResidentCount")
                        .HasColumnType("integer");

                    b.Property<int>("HousedHouseholdCount")
                        .HasColumnType("integer");

                    b.Property<int>("HousedResidentCount")
                        .HasColumnType("integer");

                    b.Property<int>("HouseholdCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MedicalLoadIndex")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RecoverySupportIndex")
                        .HasColumnType("numeric");

                    b.Property<int>("ResidentCount")
                        .HasColumnType("integer");

                    b.Property<int>("RetiredCount")
                        .HasColumnType("integer");

                    b.Property<int>("SeniorCount")
                        .HasColumnType("integer");

                    b.Property<int>("SevereIllnessCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StudentAttendanceIndex")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("StudentCommuteAccessibilityIndex")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TriagePressureIndex")
                        .HasColumnType("numeric");

                    b.Property<int>("UnemployedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WorkforceAttendanceIndex")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("WorkforceCommuteAccessibilityIndex")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("WorkforceProductivityIndex")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("YouthCount")
                        .HasColumnType("integer");

                    b.HasKey("CityId", "SnapshotDate");

                    b.HasIndex("CityId", "UpdatedAtUtc");

                    b.ToTable("CityPopulationDailySummarySnapshots", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationDeletionState", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CityId");

                    b.HasIndex("DeletedAtUtc");

                    b.ToTable("CityPopulationDeletionStates", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationEmployerFinancialStressState", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentBalanceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DistressScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<int>("FailedPayrollCount")
                        .HasColumnType("integer");

                    b.Property<bool>("HasHiringFreeze")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasLayoffPressure")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastEvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MissedGrossPayrollAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PaidGrossPayrollAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PartialPayrollCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("PayrollFulfillmentRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("RequestedGrossPayrollAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CityId", "WorkplaceId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CityPopulationEmployerFinancialStressStates", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationEnvironment", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<int>("ClimateZone")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Hemisphere")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UtcOffsetMinutes")
                        .HasColumnType("integer");

                    b.HasKey("CityId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CityPopulationEnvironments", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationEssentialsState", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EffectiveTickId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EmergencyRationingEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("EmergencyWaterShortageRiskIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("EmergencyWaterStockLevelIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("FoodShortageRiskIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("FoodStockLevelIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("MedicineShortageRiskIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("MedicineStockLevelIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("SupplyStressIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CityId");

                    b.HasIndex("EffectiveTickId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CityPopulationEssentialsStates", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationHouseholdFinancialStressState", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<int>("ArrearsObligationCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("DistressScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<int>("EvictionEligibleCount")
                        .HasColumnType("integer");

                    b.Property<int>("EvictionNoticeCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastEvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OldestOverdueAgeDays")
                        .HasColumnType("integer");

                    b.Property<int>("OverdueObligationCount")
                        .HasColumnType("integer");

                    b.Property<int>("OverdueRentCount")
                        .HasColumnType("integer");

                    b.Property<int>("OverdueUtilityCount")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceCutoffCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalOverdueAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CityId", "HouseholdId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CityPopulationHouseholdFinancialStressStates", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationLivingConditionsState", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EffectiveTickId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("FloodingIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("HeatingCoverageIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("PowerCoverageIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("RoadAccessibilityIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("SanitationCoverageIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UtilityContinuityIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("WaterCoverageIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.HasKey("CityId");

                    b.HasIndex("EffectiveTickId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CityPopulationLivingConditionsStates", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationPendingWeatherImpact", b =>
                {
                    b.Property<Guid>("ImpactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentCloudCoveragePercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateOnly>("CurrentDate")
                        .HasColumnType("date");

                    b.Property<decimal>("CurrentHumidityPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("CurrentPrecipitationKind")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentPressureHpa")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("CurrentSeverity")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentTemperatureC")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("CurrentType")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentWindSpeedKph")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int?>("EnvironmentClimateZone")
                        .HasColumnType("integer");

                    b.Property<int?>("EnvironmentHemisphere")
                        .HasColumnType("integer");

                    b.Property<int?>("EnvironmentUtcOffsetMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PreviousCloudCoveragePercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("PreviousHumidityPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("PreviousPrecipitationKind")
                        .HasColumnType("integer");

                    b.Property<decimal>("PreviousPressureHpa")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("PreviousSeverity")
                        .HasColumnType("integer");

                    b.Property<decimal>("PreviousTemperatureC")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("PreviousType")
                        .HasColumnType("integer");

                    b.Property<decimal>("PreviousWindSpeedKph")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("ImpactId");

                    b.HasIndex("CityId", "OccurredAtUtc")
                        .HasDatabaseName("IX_CityPopulationPendingWeatherImpacts_CityId_OccurredAtUtc");

                    b.ToTable("CityPopulationPendingWeatherImpacts", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationProgressionState", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastProcessedDate")
                        .HasColumnType("date");

                    b.Property<long>("LastProcessedTickId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CityId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CityPopulationProgressionStates", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationServiceQualityState", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HealthcareQualityIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("HousingSupportIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTimeOffset>("LastEvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CityId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CityPopulationServiceQualityStates", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationSummaryProjection", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveIllnessCount")
                        .HasColumnType("integer");

                    b.Property<int>("AdultCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AverageEnergy")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("AverageHappiness")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("AverageHealth")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("AverageSocialNeed")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("AverageStress")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ChildCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("date");

                    b.Property<int>("DeceasedCount")
                        .HasColumnType("integer");

                    b.Property<int>("EmployedCount")
                        .HasColumnType("integer");

                    b.Property<int>("HomelessHouseholdCount")
                        .HasColumnType("integer");

                    b.Property<int>("HomelessResidentCount")
                        .HasColumnType("integer");

                    b.Property<int>("HousedHouseholdCount")
                        .HasColumnType("integer");

                    b.Property<int>("HousedResidentCount")
                        .HasColumnType("integer");

                    b.Property<int>("HouseholdCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MedicalLoadIndex")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RecoverySupportIndex")
                        .HasColumnType("numeric");

                    b.Property<int>("ResidentCount")
                        .HasColumnType("integer");

                    b.Property<int>("RetiredCount")
                        .HasColumnType("integer");

                    b.Property<int>("SeniorCount")
                        .HasColumnType("integer");

                    b.Property<int>("SevereIllnessCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StudentAttendanceIndex")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("StudentCommuteAccessibilityIndex")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TriagePressureIndex")
                        .HasColumnType("numeric");

                    b.Property<int>("UnemployedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WorkforceAttendanceIndex")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("WorkforceCommuteAccessibilityIndex")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal?>("WorkforceProductivityIndex")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("YouthCount")
                        .HasColumnType("integer");

                    b.HasKey("CityId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CityPopulationSummaryProjections", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationWeatherExposureState", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentCloudCoveragePercent")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("CurrentHumidityPercent")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("CurrentPrecipitationKind")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentPressureHpa")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("CurrentSeverity")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentTemperatureC")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("CurrentType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CurrentWeatherEffectiveAtSimTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentWindSpeedKph")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("LastExposureProcessedAtSimTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastWeatherOccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PreviousCloudCoveragePercent")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("PreviousHumidityPercent")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("PreviousPrecipitationKind")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PreviousPressureHpa")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("PreviousSeverity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PreviousTemperatureC")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("PreviousType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PreviousWeatherEffectiveAtSimTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PreviousWindSpeedKph")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("RecoverySourceCloudCoveragePercent")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("RecoverySourceHumidityPercent")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("RecoverySourcePrecipitationKind")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RecoverySourcePressureHpa")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("RecoverySourceSeverity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RecoverySourceTemperatureC")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("RecoverySourceType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RecoverySourceWindSpeedKph")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset?>("RecoveryStartedAtSimTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CityId");

                    b.HasIndex("LastExposureProcessedAtSimTimeUtc");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CityPopulationWeatherExposureStates", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.CityPopulationWeatherImpactState", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastAppliedAtSimTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastAppliedOccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CityId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CityPopulationWeatherImpactStates", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.ClassicCityHouseholdPlacement", b =>
                {
                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("HousingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ResidentialBuildingId")
                        .HasColumnType("uuid");

                    b.HasKey("HouseholdId");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ResidentialBuildingId");

                    b.ToTable("ClassicCityHouseholdPlacements", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Infrastructure.Persistence.Entities.CityHealthcareDistrictHealthSnapshotEntity", b =>
                {
                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveIllnessCount")
                        .HasColumnType("integer");

                    b.Property<int>("PatientCount")
                        .HasColumnType("integer");

                    b.Property<int>("SevereIllnessCount")
                        .HasColumnType("integer");

                    b.HasKey("CityId", "DistrictId");

                    b.HasIndex("DistrictId");

                    b.ToTable("CityHealthcareDistrictHealthSnapshots", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Infrastructure.Persistence.Entities.CityHealthcarePressureSnapshotEntity", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveIllnessCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CurrentDate")
                        .HasColumnType("date");

                    b.Property<decimal>("MedicalLoadIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PatientCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("RecoverySupportIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<int>("SevereIllnessCount")
                        .HasColumnType("integer");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint");

                    b.Property<decimal>("TriagePressureIndex")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CityId");

                    b.HasIndex("SourceRevision");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("CityHealthcarePressureSnapshots", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Infrastructure.Persistence.Entities.EducationParticipationProjectionEntity", b =>
                {
                    b.Property<Guid>("SimulationHostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveStage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("AttendanceIndex")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<DateTimeOffset?>("AttendanceObservedAtSimTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("AttendanceSourceTickId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<decimal?>("CommuteAccessibilityIndex")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("CompletedStage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly?>("CompletedStageOn")
                        .HasColumnType("date");

                    b.Property<string>("EconomicEffectsJson")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EnrolledOn")
                        .HasColumnType("date");

                    b.Property<Guid?>("InstitutionAnchorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnrolled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ParticipationRevision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<long>("ResidentLifecycleRevision")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SimulationHostId", "ResidentId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SimulationHostId", "InstitutionId");

                    b.HasIndex("SimulationHostId", "IsEnrolled");

                    b.ToTable("EducationParticipationProjections", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Infrastructure.Persistence.Entities.ProcessedIntegrationMessage", b =>
                {
                    b.Property<string>("Consumer")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Consumer", "MessageId");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("ProcessedIntegrationMessages", (string)null);
                });

            modelBuilder.Entity("Matrix.Population.Domain.Entities.Person", b =>
                {
                    b.HasOne("Matrix.Population.Domain.Entities.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Matrix.Population.Domain.ValueObjects.EmploymentInfo", "Employment", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("EmploymentStatus");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");

                            b1.OwnsOne("Matrix.Population.Domain.ValueObjects.Job", "Job", b2 =>
                                {
                                    b2.Property<Guid>("EmploymentInfoPersonId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("JobTitle");

                                    b2.Property<Guid?>("WorkplaceAnchorId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("WorkplaceAnchorId");

                                    b2.Property<Guid>("WorkplaceId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("WorkplaceId");

                                    b2.HasKey("EmploymentInfoPersonId");

                                    b2.ToTable("Persons");

                                    b2.WithOwner()
                                        .HasForeignKey("EmploymentInfoPersonId");
                                });

                            b1.Navigation("Job");
                        });

                    b.OwnsOne("Matrix.Population.Domain.ValueObjects.LifeState", "Life", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Health")
                                .HasColumnType("integer")
                                .HasColumnName("Health");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("LifeStatus");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");

                            b1.OwnsOne("Matrix.Population.Domain.ValueObjects.LifeSpan", "Span", b2 =>
                                {
                                    b2.Property<Guid>("LifeStatePersonId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("BirthDate")
                                        .HasColumnType("date")
                                        .HasColumnName("BirthDate");

                                    b2.Property<DateTime?>("DeathDate")
                                        .HasColumnType("date")
                                        .HasColumnName("DeathDate");

                                    b2.HasKey("LifeStatePersonId");

                                    b2.ToTable("Persons");

                                    b2.WithOwner()
                                        .HasForeignKey("LifeStatePersonId");
                                });

                            b1.Navigation("Span")
                                .IsRequired();
                        });

                    b.OwnsOne("Matrix.Population.Domain.ValueObjects.MaritalInfo", "Marital", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("SpouseId")
                                .HasColumnType("uuid")
                                .HasColumnName("SpouseId");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MaritalStatus");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("Matrix.Population.Domain.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("LastName");

                            b1.Property<string>("Patronymic")
                                .HasColumnType("text")
                                .HasColumnName("MiddleName");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("Matrix.Population.Domain.ValueObjects.Personality", "Personality", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Discipline")
                                .HasColumnType("integer")
                                .HasColumnName("Discipline");

                            b1.Property<int>("Optimism")
                                .HasColumnType("integer")
                                .HasColumnName("Optimism");

                            b1.Property<int>("RiskTolerance")
                                .HasColumnType("integer")
                                .HasColumnName("RiskTolerance");

                            b1.Property<int>("Sociability")
                                .HasColumnType("integer")
                                .HasColumnName("Sociability");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("Employment")
                        .IsRequired();

                    b.Navigation("Life")
                        .IsRequired();

                    b.Navigation("Marital")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Personality")
                        .IsRequired();
                });

            modelBuilder.Entity("Matrix.Population.Domain.Scenarios.ClassicCity.Entities.ClassicCityHouseholdPlacement", b =>
                {
                    b.HasOne("Matrix.Population.Domain.Entities.Household", null)
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Matrix.Population.Infrastructure.Persistence.Entities.CityHealthcareDistrictHealthSnapshotEntity", b =>
                {
                    b.HasOne("Matrix.Population.Infrastructure.Persistence.Entities.CityHealthcarePressureSnapshotEntity", null)
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Matrix.Population.Infrastructure.Persistence.Entities.EducationParticipationProjectionEntity", b =>
                {
                    b.HasOne("Matrix.Population.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Matrix.Population.Infrastructure.Persistence.Entities.CityHealthcarePressureSnapshotEntity", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
