<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>thematrix-identity-api-dev</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\building-blocks\Matrix.BuildingBlocks.Api\Matrix.BuildingBlocks.Api.csproj"/>
    <ProjectReference Include="..\Matrix.Identity.Contracts\Matrix.Identity.Contracts.csproj"/>
    <ProjectReference Include="..\Matrix.Identity.Infrastructure\Matrix.Identity.Infrastructure.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\"/>
  </ItemGroup>

</Project>
