// <auto-generated />
using System;
using Matrix.Resources.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matrix.Resources.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ResourcesDbContext))]
    [Migration("20260417155049_AddOutboxMessages")]
    partial class AddOutboxMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Matrix.BuildingBlocks.Infrastructure.Outbox.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAttemptOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextAttemptOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "LockedUntilUtc", "NextAttemptOnUtc", "OccurredOnUtc")
                        .HasFilter("\"ProcessedOnUtc\" IS NULL");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Matrix.Resources.Domain.Scenarios.ClassicCity.Systems.CityStockpileState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("EmergencyRationingEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastEvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SupplyStressIndex")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.ToTable("CityStockpiles", (string)null);
                });

            modelBuilder.Entity("Matrix.Resources.Domain.Scenarios.ClassicCity.Systems.CityStockpileState", b =>
                {
                    b.OwnsOne("Matrix.Resources.Domain.Scenarios.ClassicCity.Systems.CityResourceStockLineState", "EmergencyWater", b1 =>
                        {
                            b1.Property<Guid>("CityStockpileStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("DemandPressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("EmergencyWaterDemandPressureIndex");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("EmergencyWaterKind");

                            b1.Property<decimal>("ResupplyReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("EmergencyWaterResupplyReadinessIndex");

                            b1.Property<decimal>("ShortageRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("EmergencyWaterShortageRiskIndex");

                            b1.Property<decimal>("StockLevelIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("EmergencyWaterStockLevelIndex");

                            b1.HasKey("CityStockpileStateId");

                            b1.ToTable("CityStockpiles");

                            b1.WithOwner()
                                .HasForeignKey("CityStockpileStateId");
                        });

                    b.OwnsOne("Matrix.Resources.Domain.Scenarios.ClassicCity.Systems.CityResourceStockLineState", "Filters", b1 =>
                        {
                            b1.Property<Guid>("CityStockpileStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("DemandPressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("FiltersDemandPressureIndex");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FiltersKind");

                            b1.Property<decimal>("ResupplyReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("FiltersResupplyReadinessIndex");

                            b1.Property<decimal>("ShortageRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("FiltersShortageRiskIndex");

                            b1.Property<decimal>("StockLevelIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("FiltersStockLevelIndex");

                            b1.HasKey("CityStockpileStateId");

                            b1.ToTable("CityStockpiles");

                            b1.WithOwner()
                                .HasForeignKey("CityStockpileStateId");
                        });

                    b.OwnsOne("Matrix.Resources.Domain.Scenarios.ClassicCity.Systems.CityResourceStockLineState", "Food", b1 =>
                        {
                            b1.Property<Guid>("CityStockpileStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("DemandPressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("FoodDemandPressureIndex");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FoodKind");

                            b1.Property<decimal>("ResupplyReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("FoodResupplyReadinessIndex");

                            b1.Property<decimal>("ShortageRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("FoodShortageRiskIndex");

                            b1.Property<decimal>("StockLevelIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("FoodStockLevelIndex");

                            b1.HasKey("CityStockpileStateId");

                            b1.ToTable("CityStockpiles");

                            b1.WithOwner()
                                .HasForeignKey("CityStockpileStateId");
                        });

                    b.OwnsOne("Matrix.Resources.Domain.Scenarios.ClassicCity.Systems.CityResourceStockLineState", "Fuel", b1 =>
                        {
                            b1.Property<Guid>("CityStockpileStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("DemandPressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("FuelDemandPressureIndex");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FuelKind");

                            b1.Property<decimal>("ResupplyReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("FuelResupplyReadinessIndex");

                            b1.Property<decimal>("ShortageRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("FuelShortageRiskIndex");

                            b1.Property<decimal>("StockLevelIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("FuelStockLevelIndex");

                            b1.HasKey("CityStockpileStateId");

                            b1.ToTable("CityStockpiles");

                            b1.WithOwner()
                                .HasForeignKey("CityStockpileStateId");
                        });

                    b.OwnsOne("Matrix.Resources.Domain.Scenarios.ClassicCity.Systems.CityResourceStockLineState", "Medicine", b1 =>
                        {
                            b1.Property<Guid>("CityStockpileStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("DemandPressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("MedicineDemandPressureIndex");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MedicineKind");

                            b1.Property<decimal>("ResupplyReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("MedicineResupplyReadinessIndex");

                            b1.Property<decimal>("ShortageRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("MedicineShortageRiskIndex");

                            b1.Property<decimal>("StockLevelIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("MedicineStockLevelIndex");

                            b1.HasKey("CityStockpileStateId");

                            b1.ToTable("CityStockpiles");

                            b1.WithOwner()
                                .HasForeignKey("CityStockpileStateId");
                        });

                    b.OwnsOne("Matrix.Resources.Domain.Scenarios.ClassicCity.Systems.CityResourceStockLineState", "SpareParts", b1 =>
                        {
                            b1.Property<Guid>("CityStockpileStateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("DemandPressureIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SparePartsDemandPressureIndex");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SparePartsKind");

                            b1.Property<decimal>("ResupplyReadinessIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SparePartsResupplyReadinessIndex");

                            b1.Property<decimal>("ShortageRiskIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SparePartsShortageRiskIndex");

                            b1.Property<decimal>("StockLevelIndex")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("SparePartsStockLevelIndex");

                            b1.HasKey("CityStockpileStateId");

                            b1.ToTable("CityStockpiles");

                            b1.WithOwner()
                                .HasForeignKey("CityStockpileStateId");
                        });

                    b.Navigation("EmergencyWater")
                        .IsRequired();

                    b.Navigation("Filters")
                        .IsRequired();

                    b.Navigation("Food")
                        .IsRequired();

                    b.Navigation("Fuel")
                        .IsRequired();

                    b.Navigation("Medicine")
                        .IsRequired();

                    b.Navigation("SpareParts")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
